### ISSUE TITLE
Step-by-step Guide

### ISSUE THREAD

**Issue by nikmd23** [sjkp/letsencrypt-siteextension#10]
I've published a step-by-step guide for how to use this site extension, if you or the users of the project find it helpful: https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/

**Comment by sjkp** [comment]
Super! I will link to it from the readme.

**Comment by sjkp** [comment]
Btw - I am planning on making the installation a lot easier. So stay tuned :)

**Comment by nikmd23** [comment]
Great! I saw you did a release yesterday, so I updated my document slightly to match that update.

If you ping me on Twitter or Gmail (I have the same handles there as I do here), then I'll keep the article up to date as you make things better and better.

Feel free to close this issue whenever you'd like.

**Comment by sjkp** [comment]
I have added some official docs to the wiki https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install - I will make sure these are up-to-date. 
@nikmd23 thanks again for writing the article and promoting the plugin

**Comment by nikmd23** [comment]
Thank you!
