### ISSUE TITLE
Disable overwriting existing web.config in acme-challenge folder

### ISSUE THREAD

**Issue by Niels-V** [sjkp/letsencrypt-siteextension#103]
I do have the need to edit the generated web.config in the acme-challenge folder. In my case (enabling the site extension in my OrchardCMS website) I need an access policy on the handler node specified:
```
    <handlers accessPolicy="Script,Read">
        ...
    </handlers>
```
But every time the webjob is triggered, my edit is overwritten with the hardcoded web.config contents. 

As there is another fix for webforms anonymous access (#101) which is basically the same issue, how about generating a switch in the settings, and when it's set, do not overwrite the web.config with the predefined web.config version. 

My work-around is currently submitting the job manually, and edit the web.config back just in time the challenge is requested by let's encrypt.

**Comment by sjkp** [comment]
Hi @Niels-V try the lastest version 0.5.9 it adds an extra web application settings `letsencrypt:DisableWebConfigUpdate` that can be set to true if you want to provide your own web.config in the acme-challenge folder.

**Comment by Niels-V** [comment]
As it is 3 months later now, I upgraded to the greatest and latest and can confirm it works flawlessly. Big thanks for this implementation!
I  noticed this setting isn't mentioned in the index.cshtml file, so I added in the Azure Portal application settings directly.
