### ISSUE TITLE
Adding & securing additional hostnames on an existing Azure web app

### ISSUE THREAD

**Issue by ephraimm** [sjkp/letsencrypt-siteextension#105]
I've setup a wildcard subdomain on our DNS with correct A and CNAME records for azure to identify ownership of our site. (*.mydomain.com)

The next step is to add a host name to the web app (app1.mydomain.com) which is working - still need to figure out how to script that part.

The part I need help with is, can you automate/script the adding of a hostname to an existing web app and generate a certificate for it with your extension?

Ultimately I'd like to be able to add:

app2.mydomain.com
app3.mydomain.com
.
.
.
app99.mydomain.com
etc. and generate certificates for each.

**Comment by sjkp** [comment]
Hi @ephraimm please see this ARM template on how to add hostnames using the ARM template. https://github.com/sjkp/Azure.ARM.CustomHostnameFunction/blob/master/Azure.ARM.CustomHostnameFunction/azuredeploy.json#L132-L147 

Let me know if that answers your question.
