### ISSUE TITLE
Support for Azure Functions

### ISSUE THREAD

**Issue by dmarlow** [sjkp/letsencrypt-siteextension#111]
I tried adding a web.config to the wwwroot and adding the rewrite but it still didn't work. Anyone know if it's possible to add this site extension on an Azure Function service?

The error is that this is unreachable: `The Lets Encrypt ACME server was probably unable to reach http://<site>/.well-known/acme-challenge/<challenge> view error report from Lets Encrypt at https://acme-v01.api.letsencrypt.org/acme/authz/Dt41TQbSUEGA1CMhaf-Qc-7R7Z489kG8meJ2iouTlpY for more information`

**Comment by sjkp** [comment]
Hi @dmarlow 
It is not something I have tested, but I expect it to be possible, I will check it out this weekend. And let you know how to do so.

**Comment by sjkp** [comment]
@dmarlow here's a work around for now, I might integrate it better in the future, but this should unblock you:
https://github.com/sjkp/letsencrypt-siteextension/wiki/Azure-Functions-Support 

Obviously if you are on the dynamic plan, the web job will not be able to renew the certificate, so until I provide an alternative way to do it, you have to renew the certificate yourself every 3 months.

**Comment by dmarlow** [comment]
Works perfectly. Thanks for the write-up and all of your time on this project!
