### ISSUE TITLE
Extension with Laravel

### ISSUE THREAD

**Issue by rafael-franca** [sjkp/letsencrypt-siteextension#113]
I tried use the extension with Laravel, but received the error:

The Lets Encrypt ACME server was probably unable to reach http://domain.com/.well-known/acme-challenge/SXxG-TBVwZ0aFYq0eA5HKfKMq9Nr6yi6EM9YcGg2Ai8 view error report from Lets Encrypt at https://acme-v01.api.letsencrypt.org/acme/authz/AYSj9m0nQfv_9JyTtHUH0NSak_x4C8QnL9q1t-KIsOU for more information...

I suspect the error is associated with web.config.

Can you help me?

Best Regards,
Rafael França

**Comment by rafael-franca** [comment]
In Azure Portal > Your App > App Settings, add "letsencrypt:WebRootPath" as key, and "your directory" as value, in my case, the value is "D:\home\site\wwwroot\public".

I suggest you add this information in the instructions.

Thanks

**Comment by sjkp** [comment]
@rafael-franca thans for the information. Added it to the wiki page.
