### ISSUE TITLE
"Azure App Services Environment" in the installation guide is a misleading term

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#115]
"App Services Environment" is a premium (expensive) Azure offering:
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-app-service-environment-intro

I'm not exactly sure what you mean by "App Services Environment" in the [installation guide](https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install), but it's probably not this...

**Comment by sjkp** [comment]
It was never intended to be understood as ASE, just an "environment" (plan + web site). But I have removed environment from it now, to avoid confusion. Thanks for the input.
