### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by gituser227** [sjkp/letsencrypt-siteextension#121]
After reaching the final stage (/letsencrypt/Home/Install) there is this error:
[HttpRequestException: Response status code does not indicate success: 403 (Forbidden).]
   System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() +91716
   LetsEncrypt.SiteExtension.Core.Services.CertificateService.Install(ICertificateInstallModel model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\CertificateService.cs:56

In Kudu, checking /SiteExtensions/letsencrypt/config/{AcmeBaseUri} it looks like certs were actually retrieved, since there are are a number of files like the following:
{domain}-all.pfx
{domain}-crt.der
{domain}-crt.pem
{domain}-csr.pem
{domain}-gen-csr.json
{domain}-gen-key.json
{domain}-key.pem
ca-{long character string}-crt.der
ca-{same long character string}-crt.pem
Registration
Signer

**Comment by sjkp** [comment]
It fails at the step where it is installing the certificate to the service plan resource group. Do the service principal have access to the that resource group, or does it maybe only have access to the resource group of the web app?

**Comment by gituser227** [comment]
BINGO! Thanks Simon!

I followed up with the IT guy that handled the service principal. It was not configured correctly. It had been given Reader role instead of Contributor.
After taking care of that, from start to finish it was a smooth and successful process. Cert acquired and installed.

**Comment by ryanwebjackson** [comment]
A quick note - I got the same error, but the principal was given the Contributor role to the wrong subscription.
