### ISSUE TITLE
AzureWebJobsStorage and AzureWebJobsDashboard connection strings

### ISSUE THREAD

**Issue by kairovs** [sjkp/letsencrypt-siteextension#124]
Hi,
I have a question on how to setup automatic certificate renewal using Web jobs. By default after installing extension Web jobs are not working because connection strings are not defined. Confusing part is that I was not able to find something about it in the documentation so I assumed that I need to set 2 connection strings (AzureWebJobsStorage and AzureWebJobsDashboard) to my storage account. Is my assumption correct? Its a bit strange setting the same connection string for both AzureWebJobsStorage and AzureWebJobsDashboard.
Then I noticed about the Azure Functions support (https://github.com/sjkp/letsencrypt-siteextension/wiki/Azure-Functions-Support) - does that means it can be used instead of Web jobs?
It would be really helpful to cover these topics in Wiki.
Otherwise - really good product, works nicely.
Thanks you!

**Comment by sjkp** [comment]
Hi @kairovs thanks for your feedback. I it is true that you have to create both connection strings, as that is how Azure Web Jobs define it. 

It is also true that I'm working on Azure Function support (currently the only support is that you can install the SSL certificate on a azure function web app). I will sometime next week release some information on how you can use azure functions instead of the web jobs, but it is not ready yet.

**Comment by SviFi** [comment]
**Hi SJKP, thank you for a great extension!**

Any new developments with the Azure Function support? 

I am actually having a strange problem with WebJobs approach. It keeps restarting **restart pending** status all the time. If I check the WebJob logs it says 

> "...Failed to connect with the ABC storage account using credentials provided in the connection string..." 

I have checked the connection string in AzureWebJobsStorage and AzureWebJobsDashboard app settings are exactly like it appears on storage account's access keys page.
I have even re-created the storage account just in case - did not help. What could I check? Thank you!

**Comment by SviFi** [comment]
@sjkp 

Found a reason! I was specifying the connection string exactly like in Storage Account settings, which looks like this: `"DefaultEndpointsProtocol=https;AccountName=ABC;AccountKey=...;EndpointSuffix=core.windows.net"`
It includes extra parameter at the end "EndpointSuffix", which caused the problem!

So, I removed it and in started to work! 
`"DefaultEndpointsProtocol=https;AccountName=ABC;AccountKey=..."`

**Comment by sjkp** [comment]
@SviFi  thanks - that is something new, I wasn't aware of.

**Comment by Kofl** [comment]
Maybe someone can update the installation documentation? Had thensame troubles as mentioneted in that bug.Thx

**Comment by sjkp** [comment]
The next release will fix it so that you can supply the connection string in the new format.
