### ISSUE TITLE
Stuck in pending state

### ISSUE THREAD

**Issue by andrewgluh** [sjkp/letsencrypt-siteextension#125]
Each time I request a certificate, I get the error below.
I am using the latest version of the extension (0.6.16)

[Exception: Unable to complete challenge with Lets Encrypt servers error was: pending]
   LetsEncrypt.SiteExtension.Core.Services.<RequestCertificate>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:61
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   LetsEncrypt.SiteExtension.Core.<RequestAndInstallInternalAsync>d__10.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:150
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   LetsEncrypt.SiteExtension.Controllers.<Install>d__7.MoveNext() +826
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +93
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +178
![error](https://cloud.githubusercontent.com/assets/27728506/25130335/238a6f3c-2485-11e7-890d-5f29b15f7203.png)

**Comment by sjkp** [comment]
Did you check that you can browse the challenge file?

**Comment by andrewgluh** [comment]
yes, the challenge file is there with content

**Comment by sjkp** [comment]
Can you browse it? on http://<yoursite-dns-name>/.well-known/acme-challenge/yNQ-.......

**Comment by andrewgluh** [comment]
Yes, I can view the file in the browser. The file contents look valid.

**Comment by sjkp** [comment]
If you try to install 0.6.17 it should throw an exception with a link to the Lets Encrypt status page, if it is still unable to get out of pending state (I have increased the amount of time it waits a bit too, which maybe could fix your problem).

**Comment by andrewgluh** [comment]
Thanks very much Simon!
I have updated to 0.6.17. Below is the error from the Let's Encrypt link.

I have checked that the DNS has propogated here: https://www.whatsmydns.net/#A which it has.
Any ideas?

{
  "identifier": {
    "type": "dns",
    "value": "[xxx].com.au"
  },
  "status": "invalid",
  "expires": "2017-04-25T21:58:15Z",
  "challenges": [
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/Sp4aP3Bz-Wdp5FI82kqu1NeKNg6Ib3e7q-EptEblwms/34807577",
      "token": "RWg3i5uuC6rf6-rRkcM3sZhGdTIPiPg8kpyEwOCdwJE"
    },
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "DNS problem: SERVFAIL looking up CAA for [xxx].com.au",
        "status": 400
      },
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/Sp4aP3Bz-Wdp5FI82kqu1NeKNg6Ib3e7q-EptEblwms/34807578",
      "token": "OU7nqil4aMN2fy1GYY-W-WDH-KgN3OHv0uIPx3ssUVQ",
      "keyAuthorization": "OU7nqil4aMN2fy1GYY-W-WDH-KgN3OHv0uIPx3ssUVQ.reFwlhmS5f5XmmCUmvTyqQ0cOJXb6jhk-3p-cT-xgxI",
      "validationRecord": [
        {
          "url": "http://[xxx].com.au/.well-known/acme-challenge/OU7nqil4aMN2fy1GYY-W-WDH-KgN3OHv0uIPx3ssUVQ",
          "hostname": "[xxx].com.au",
          "port": "80",
          "addressesResolved": [
            "191.xxx.xxx.xx"
          ],
          "addressUsed": "191.xxx.xxx.xx"
        }
      ]
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/Sp4aP3Bz-Wdp5FI82kqu1NeKNg6Ib3e7q-EptEblwms/34807579",
      "token": "l980-gZ7ILRZP1It6qkTj5IjcjL205MSKCqDC_ffDfM"
    }
  ],
  "combinations": [
    [
      2
    ],
    [
      0
    ],
    [
      1
    ]
  ]
}

**Comment by andrewgluh** [comment]
Ok, it looks like an issue with the DNS provider (NetRegistry).
It seems other Let's Encrypt users have had issues with them: https://community.letsencrypt.org/t/dns-query-timed-out/5353/23

**Comment by sjkp** [comment]
@andrewgluh my only suggestion would be to try a CNAME record instead (if that is possible), unfortunately there not much I can do in regards to DNS configuration, so I will close the issue. Feel free to write the resolution if you find one.
