### ISSUE TITLE
The wwwroot/.well-known path is not an available route in Azure node.js web apps

### ISSUE THREAD

**Issue by tim-wilcoxson** [sjkp/letsencrypt-siteextension#126]
The wwwroot/.well-known path is not an available route in Azure Node.JS apps.  The challenge files would have to be created /public to be served by the external request from letsencrypt.  Basically this breaks things.  I had to write a continuous copy to move the challenge directory over to public to get the validation to work.  I'm new to letsencrypt, but assuming the validation happens again at renewal with a new validation file then this would be broken unless I continued to copy or figured out a way to route to .well-known.   

Anyway to support change the location of the challenge files?

**Comment by sjkp** [comment]
You can set the following app setting, if you dont want the challenge files to be placed in the default wwwroot

`letsencrypt:WebRootPath`	Use this setting, if you are not serving the website from site\wwwroot, then you can sepecify the other folder that serves your website here - should be in the format d:\home\site\wwwroot\public or where ever your files are located on the web server.

**Comment by sjkp** [comment]
You can also take a look at #27

**Comment by tim-wilcoxson** [comment]
Thanks. I think we are just going to go with the web.config rewrite.

<rule name="AcmeContent">
     <match url=".well-known/acme-challenge/*" />
     <action type="Rewrite" url="{REQUEST_URI}"/>
</rule>

Seems to be working.
