### ISSUE TITLE
Cannot find the GUI part of the installation anywhere

### ISSUE THREAD

**Issue by MrCsabaToth** [sjkp/letsencrypt-siteextension#130]
I did not get presented with any GUI interface and I cannot find it anywhere as well. I believe I performed the proper configuration, creating a Principal and setting all of the WebApp Settings variables.
See more: https://serverfault.com/questions/847416/where-is-azure-lets-encrypt-extensions-gui

**Comment by sjkp** [comment]
@MrCsabaToth i replied to your serverfault post. Please close this, if it helps.

**Comment by MrCsabaToth** [comment]
The UI was indeed at https://[your-webapp].scm.azurewebsites.net/letsencrypt as you indicated. Thanks! Now I just need to get it working.
