### ISSUE TITLE
Site returns default *azurewebsites.net certificate

### ISSUE THREAD

**Issue by pointlevel** [sjkp/letsencrypt-siteextension#132]
Hello! 

I have been using this extension for a while and really like it. Im using it for several sites, but now im struggling with one of them. The certificate suddenly stopped working, and the webserver is returning the azure default certificate *.azurewebsites.net. I have issued a new certificate and bind it to the website, tried both IP SSL and SNI SSL, but i cant get the server to return my certificate.
Do you have any ideas about this?

**Comment by tiagorz** [comment]
I have the same problem, did you solve it?

**Comment by tiagorz** [comment]
Help Me @pointlevel!!!!!

**Comment by sjkp** [comment]
Is the certificate installed, i.e. can you see it listed in the portal and it is assigned to a hostname? If so I would open a support ticket with MS.

**Comment by pointlevel** [comment]
This problem was a while ago, and i really cant remember the exact solution. But i think it was some caching-problem locally in my computer. So probably the cert-update fixed the actual problem, but i thought it was not, because of the cache. Try to clear cache in your browser.
