### ISSUE TITLE
Install WebJobs manually

### ISSUE THREAD

**Issue by minhnhat2807** [sjkp/letsencrypt-siteextension#133]
At the first time, I installed Letsencrypt successfully and a web job created. Now the WebJobs is disappear (maybe it's deleted by co-worker or when we tried to re-deploy application), I tried Request & Install Certificate again but WebJobs is not installed so the question is "Can I add WebJobs manually and how?"

Thanks

**Comment by sjkp** [comment]
You can just uninstall the site-extension and install it again (all settings should be stored, so you don't have to reconfigure it). There is no option to reinstall the web job seperately, as of right now.
