### ISSUE TITLE
Azure "Browse" button greyed out

### ISSUE THREAD

**Issue by frenchviking** [sjkp/letsencrypt-siteextension#134]
I'm using this great extension for many month now for few App Services. Today, while adding a new App service I wanted to add and configure the extension. This was impossible because the "Browse" button (App Service --> MyApp --> Extensions --> Azure Let's Encrypt (x64) is greyed out. And while everything was fine for my previous App service's installation, the button is greyed out as well for them now.
My App service is a 64 bits platform, I tied to restart it, to reinstall the extension, to update it... No success.

**Comment by sjkp** [comment]
Sounds like a portal bug:
![image](https://cloud.githubusercontent.com/assets/3397744/25719891/3cbf73fc-310b-11e7-933e-81383ac336c7.png)
This is what it looks like for me assume it is the same for you. 

It is not a big deal however, you should be able to browse the extension using `https://[websitename].scm.azurewebsites.net/letsencrypt`

**Comment by sjkp** [comment]
I opened an issued with the kudu team https://github.com/projectkudu/kudu/issues/2422

**Comment by kspearrin** [comment]
> Btw. the site extensions are still browsable, by manually typing in the full url, it is just the UI to browse to them that is not working.

What is the manual URL I can use to access?
