### ISSUE TITLE
.6.17 Doesn't allow Browse, or Play on Azure (Launching Extension)

### ISSUE THREAD

**Issue by Rumple-Phillip** [sjkp/letsencrypt-siteextension#135]
Updated to .6.17, and cannot 'browse' to the extension or run it in Kudu any longer. Ergo, I have no way of launching this extension. 

http://i.imgur.com/mfKpEdJ.png

Picture for example, showing no actual 'Play' button in Kudu to launch the extension. 

http://i.imgur.com/XDni4lf.png

Picture, for example, showing that 'browse' no longer functions after update. 

I removed the extension and added it back, same result. 

--Phillip

**Comment by kspearrin** [comment]
Same

**Comment by kspearrin** [comment]
Duplicate: https://github.com/sjkp/letsencrypt-siteextension/issues/134

**Comment by sjkp** [comment]
Unfortunately there is nothing I can do to fix this. So we have to wait for Microsoft.
