### ISSUE TITLE
Azure site Extentions - Feilds

### ISSUE THREAD

**Issue by syleshnair** [sjkp/letsencrypt-siteextension#136]
Hi there ,
 I was configuring letsEncrypt. and I was wondering how to get this  page for setting the 
Tenant ,
SubscriptionId 
ClientId
ClientSecret -
ResourceGroupName 

![image](https://cloud.githubusercontent.com/assets/28474523/25770299/e779e850-324f-11e7-9f12-c39959d2a32b.png)

Please advice

**Comment by k-miyake** [comment]
Is your question the same as this?
https://serverfault.com/questions/847416/where-is-azure-lets-encrypt-extensions-gui

**Comment by sjkp** [comment]
Please see #134
