### ISSUE TITLE
Unable to start extension in Azure scm portal

### ISSUE THREAD

**Issue by jwooley** [sjkp/letsencrypt-siteextension#137]
After installing the extension following the instructions at https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/20047 at the mysite.scm.azurewebsites.net and restarting the site, I am unable to see the play button. I've tried both the x86 and x64 versions and neither appear to respond correctly. I don't know if this caused by issues with new builds or something in my configuration, nor am I sure how to debug issues with it. 

Checking the networking traffic, the install request completes with a provisioningState of "Succeeded". The Restart site request returns a "502: Bad Gateway" response.

**Comment by willvlad** [comment]
Having the same issue. All the letsencrypt certificates installed previously seem to be failing now. And there is no play button to install new ones despite re-installing several times both x86 and x64 versions. 
Please fix this ASAP as my azure sites are not loading without a valid certificate.

**Comment by JamesRandall** [comment]
The missing play button is due to a bug in Kudu:
https://github.com/projectkudu/kudu/issues/2422

**Comment by sjkp** [comment]
@jwooley please close this if @JamesRandall suggestion works. 

I'm sorry for the inconvenience, but hard for me to do anything when MS introduces bugs.

**Comment by jwooley** [comment]
Thanks @JamesRandall. Able to access the extension now.
