### ISSUE TITLE
Azure : Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided. Trace ID

### ISSUE THREAD

**Issue by abaazzi** [sjkp/letsencrypt-siteextension#144]
Hello, 

When I renewed the SSL certificate I got the error message:

Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided. Trace ID: a1daagbb-5047-4c59-170e-ceegeg52590200 Correlation ID: 367371g4-39c0-459c-b506-61937a4d76475 Timestamp: 2017-06-08 09:22:07Z ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized. at System.Net.HttpWebRequest.GetResponse() at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext() --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, ClientCredential clientCredential) at LetsEncrypt.SiteExtension.ArmHelper.GetToken(IAzureEnvironment model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 30 at LetsEncrypt.SiteExtension.ArmHelper.GetWebSiteManagementClient(IAzureEnvironment model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 18 at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model) ErrorCode: invalid_client StatusCode: 401

**Comment by sjkp** [comment]
Could it be that the client secret you are using have expired. Per default they only last a year, if it was created in the old portal.

**Comment by abaazzi** [comment]
Hello
Thank you very much for your help.
