### ISSUE TITLE
Not found WebJob

### ISSUE THREAD

**Issue by MarxiRo** [sjkp/letsencrypt-siteextension#145]
Hi
I have a problem 
After installed site extension and request and install certificate 
I go to webjob in azure portal in app service 
Then I didn't see any webjob run 

please let me know what should I do wrong

**Comment by Tsaukpaetra** [comment]
I fixed this myself by deleting and re-adding the extension. Apparently the extension doesn't repair the webjob if it's broken or deleted...

**Comment by MarxiRo** [comment]
I will try to do

Thank you for your solution.

2017-07-19 1:24 GMT+07:00 Tsaukpaetra <notifications@github.com>:

**Comment by sjkp** [comment]
@MarxiRo that solve your problem? If so please close the issue.

**Comment by sjkp** [comment]
Closing as of no feedback.
