### ISSUE TITLE
silent WebException when using blob storage account kind.

### ISSUE THREAD

**Issue by Bartmax** [sjkp/letsencrypt-siteextension#148]
I used this extension with a `Blob storage account kind`. 

![image](https://user-images.githubusercontent.com/3386797/27514377-1d97f8c4-595f-11e7-91b7-83c5cf091712.png)

Everything worked fine when I installed it, but today I discovered that logs shows that the extension is run very often and fails with 

```
Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: 
The remote name could not be resolved: 'xxx.queue.core.windows.net' ---> 
System.Net.WebException: The remote name could not be resolved: 'xxx.queue.core.windows.net'
```

1) is it possible to make it work with blob storage only accounts? if not, it would be great to add to the doc/readme. Specially because it fails silently (unless you look around) and you cannot (or didn't find how) to change from one account kind to another.

2) How bad is my current scenario? What is queue used for?

**Comment by sjkp** [comment]
The web jobs sdk uses queues internally. So yes it is required to use a general purpose storage account. 
https://github.com/Azure/azure-webjobs-sdk/issues/797 
Will make it cleared in the documentation.

**Comment by ohadschn** [comment]
I created a WebJob without the WebJob SDK so no storage account of any kind is required:
https://github.com/ohadschn/letsencrypt-webapp-renewer
