### ISSUE TITLE
The Lets Encrypt ACME server was probably unable to reach

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [sjkp/letsencrypt-siteextension#150]
Hi @sjkp ,

We are trying to issue a new certificate for a website, but we saw a strange error today, it was fine in the past for the other domains.

![error](https://user-images.githubusercontent.com/4378651/27792531-70f7dd1c-5ffa-11e7-86e7-0dc74ac89fba.png)

We checked the response it mentioned 'urn:acme:error:unauthorized' 'invalid response not found'
![request ssl](https://user-images.githubusercontent.com/4378651/27792416-ea79ec08-5ff9-11e7-97b0-8e90db306938.png)

But when I open the same URL it does return the same token, and the file was on the server also.
![acme-challenge](https://user-images.githubusercontent.com/4378651/27792430-f9bfe7b2-5ff9-11e7-8c45-d3aed9b90174.png)

I am lost now, would be great if you could help me out.

**Comment by sjkp** [comment]
Seems strange. 
Do you have multiple web apps, that you are load balancing between? Or do you maybe have a web slot, that some traffic is routed too? 

Also it seems fishy that the status is 403, but the detail text says it was a 404.

**Comment by zhangpeng-kooboo** [comment]
@sjkp We only have one web app installed let's encrypt, and there has only one slot also. I refreshed a few times the URL it does shows the same token. Look a bit strange.

**Comment by sjkp** [comment]
Did some extra digging, it seems like an NSlookup on your domain returns the IPv6 address before the IPv4 adresse, letsencrypt reports that IPv6 was used 
```
"addressUsed": "2a06:2ec0:1::107",
```
How ever if I browse that URL http://[2a06:2ec0:1::107]/, it don't get routed to azure. 

I don't exactly know how this is supposed to work with IPv6, none of my sites have IPv6 configured. If you want to get to bottom of it I suggest that you ask on the letsencrypt forum. If you just want it fixed, you need to figure out why an NSlookup for your domain returns an the IPv6 first, and change that.

**Comment by zhangpeng-kooboo** [comment]
Thks @sjkp  I will try to figure out the IPv6 with the DNS provider. That could explain the issue why only this domain does not work 👍

**Comment by sjkp** [comment]
@zhangpeng-kooboo did you find a solution?

**Comment by lucassantosTI** [comment]
I had same problem, I discover this occurs with an webapp using TLS (require a client certificate) and forcing HTTPS(443) connections via Rewrite Rule in web.config, to solve problem i'm remove the rule and after certificate installation re-write the rule and all take on ok.

**Comment by zhangpeng-kooboo** [comment]
@sjkp sorry, I forgot to update the issue, after we asked the dns provider to remove IPv6 from our customer's domains, it fixed the issue.

**Comment by sjkp** [comment]
@zhangpeng-kooboo  thanks for reporting back, will potentially help other people in the future 👍
