### ISSUE TITLE
What is the minimum app service plan tier?

### ISSUE THREAD

**Issue by Luis-Palacios** [sjkp/letsencrypt-siteextension#152]
Hello,

I notice while looking at the guide [here](https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/21872#.WW49gYTysuU) that the minimum is Standart but among the comments, some said that now it supports the shared tier and while look at the official installation guide on the wiki here I was not able to find anything regarding that. 

So can I use this on a shared tier?

Thanks for the awesome extension.

**Comment by sjkp** [comment]
SSL is only available in basic, standard and preium plans unfortunately. https://azure.microsoft.com/en-us/pricing/details/app-service/

**Comment by Luis-Palacios** [comment]
Ok thanks, for the response!
