### ISSUE TITLE
Uri format issue

### ISSUE THREAD

**Issue by cdeli** [sjkp/letsencrypt-siteextension#153]
`System.ArgumentException: 'authority' should be in Uri format Parameter name: authority at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator.DetectAuthorityType(String authority) at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator..ctor(String authority, Boolean validateAuthority) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(String authority) at LetsEncrypt.SiteExtension.ArmHelper.GetToken(IAzureEnvironment model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 28 at LetsEncrypt.SiteExtension.ArmHelper.GetWebSiteManagementClient(IAzureEnvironment model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 18 at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model)`

Getting that error no matter what I do. I double checked and the service account is set as contributor to bot the RG and the app itself. Using the x86 extension as well.

**Comment by sjkp** [comment]
What did you use as the tenant information? Your tenant GUID? or tenanname.onmicrosoft.com ?

**Comment by cdeli** [comment]
I used the Tenant Name. Did not use the GUID yet though.

**Comment by cdeli** [comment]
adding the tenantname.onmicrosoft.com did the trick. I would add something like that to the documentation for this just to be safe with people like me who miss it.
