### ISSUE TITLE
Web Jobs in Deployment Slots not working

### ISSUE THREAD

**Issue by dhilgarth** [sjkp/letsencrypt-siteextension#154]
I have a web app with 4 deployment slots. The default / production and three for different testing stages.
I have enabled the Lets Encrypt Site Extension on each slot. Also, each slot has the Web Job enabled.

But only the production slot actually renews its certificate, the others don't.
On all four slots Functions.Cleanup always fails. RenewCertificate and AddCertificate are successful on all slots.

How can I troubleshoot this?

Thanks!

**Comment by sjkp** [comment]
Did you fill out the siteslotname setting during the configuration?

![image](https://user-images.githubusercontent.com/3397744/28941094-298ea9aa-7897-11e7-921e-7842c3524864.png)
On the picture you can see that I'm using a site slot named vnext.

**Comment by sjkp** [comment]
@dhilgarth just looked at the code again and did some more testing, it turns out there was a bug in the renew web job. It will be fixed in the next release. Sorry for the inconvenience.

**Comment by dhilgarth** [comment]
Great, thanks!
