### ISSUE TITLE
Functions.RenewCertificate throwing 504 Gateway Timeout Errors

### ISSUE THREAD

**Issue by modemgeek** [sjkp/letsencrypt-siteextension#155]
We had a bunch of certificates expire.  We never got an email notification nor did the certificates auto-renew.  Looking at the webjobs logs file, I see the same 504 error daily.  Andy idea what could be causing this?

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.RenewCertificate ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 504 (Gateway Timeout).
 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 at LetsEncrypt.SiteExtension.Core.CertificateManager.<RenewCertificate>d__8.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:line 82
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at LetsEncrypt.SiteExtension.Functions.<RenewCertificate>d__1.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.WebJob\Functions.cs:line 61
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of inner exception stack trace ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__1.MoveNext()

**Comment by sjkp** [comment]
Hmm, that timeout is coming from the ARM api, the endpoint that should return which certificates you have in your subscription. 

Are you able to browse `https://resources.azure.com/subscriptions/[Your-SubscriptionId]/providers/Microsoft.Web/certificates` or does that give the 504 as well?

**Comment by modemgeek** [comment]
You are correct.  It does give a 504.  The problem we had is many of our certificates expired.  We are not sure why auto renew is failing and why we didn’t get any notifications that they are expiring.  We tried getting new certs, but kept getting the 504.  We discovered that it was getting the new certificate but was not binding it to the host name in azure.  Binding it manually from Azure is working.  I’ll see what Microsoft has to say.  They first said it’s not us as usually so showing them that we get the same error from resources.azure.com might help out.  Thank you.

**Comment by sjkp** [comment]
The missing emails is probably due to the fact that the certificate was renewed, just not installed. The emails are sent by Lets Encrypt not by the extension. And I guess Lets Encrypt just check that the cert was renewed and then assumes it is installed and assigned.

**Comment by sjkp** [comment]
@modemgeek did microsoft help you out or provide any more info?

**Comment by modemgeek** [comment]
they said they made some updates but didn't go into much details.  I'm not seeing the 504 errors from the webjobs logs, however I do see this error now.  I know what is causing it, but does that mean when it encounters an error, the processing of renewals stops?  The status says failed?  We run up to 100 sites on a single webserver and each site has their own certificate.  If it fails to renew one, does it stop or will it continue to renew the others?

The Lets Encrypt ACME server was probably unable to reach http://blahblah.com

**Comment by modemgeek** [comment]
Here's their response:

The response from the Product Group is that the best option is to use Azure CLI to script the enumeration of the certificates.  The problem being seen in this case involves a PowerShell bug that will be prioritized with other bug fixes with no ETA at this time. 
 
The expectation is that to run a script for the number of sites in your subscription, it will be more reliable and stable in a production environment to use Azure CLI.   Although there is not a way to check web apps directly by referring to the  subscription number, it should be possible to list the resource groups, and then iterate through those to get the web apps.

**Comment by modemgeek** [comment]
they also said running this in powershell is the same as viewing it from resource manager.  The powershell cmdlet stopped returning a 504 error now but giving this instead.  I think it goes back to "we have too many certificates in our account" and although we don't get a time out, azure is not able to handle it

**Comment by sjkp** [comment]
A powershell bug, wth. This is their ARM API, I'm assuming their Azure CLI uses the same API. I will looping in the PM of the Azure Resource Manager. Can't be real that they have an API that is broken if you have a large amount of certificates. 
One thing you can try though, is to remove some of the expired certificates manually, the extension didn't clean up in the beginning and because of the timeout I'm guessing it is unable to clean up automatically now. 

How many certs do you have in there? I might want to try to break one of my own subscriptions to help you out.

**Comment by sjkp** [comment]
To clean them up you have to do it per resource group, if you have trouble with that, let me know and I can make script for you tomorrow.

**Comment by modemgeek** [comment]
thanks.  we have a script the that iterates through all the subscriptions and resource groups and deletes the certificate if it is not bound.  we deleted about 300 unused certificates.  Last time I checked we have about 1200-1300 certificates spread across 30 webapps.  

Actually if you do have a script that cleans up, can you share?  Maybe it runs faster than ours.  It takes up to 2 hours to complete when we run ours

**Comment by sjkp** [comment]
I don't have one, would have to make it. Shouldn't run that long, are you doing it sequentially?

**Comment by modemgeek** [comment]
yes, we get the list of webapps and store then in an array and then it iterates through all of them one by one

**Comment by modemgeek** [comment]
This issue seems to have came back .  I'm seeing a mixed of "Never Finished" when running the RenewCertificate function, or "Failed" with the error 504 timeout or it says it could not it could not reach the domain.  However, instead of doing the RenewCertificate function and I try just adding it again, it completes without any problem.  It's like it takes too long to complete and times out.  Another observation I have seen is that when it comes across a domain that we no longer host, the renewcertificate function stops.  Is there any way we can have it continue processing other renewals, even if one errors out?
