### ISSUE TITLE
0.7.3 Nupkg is only 3kb; Extension Missing?

### ISSUE THREAD

**Issue by toby-meyer** [sjkp/letsencrypt-siteextension#156]
Hi Simon, thanks much for the great extension. It looks like there may be a packing error in the nupkg file hosted on the siteextensions.net site. After installing via the portal and using kudu tools to browse to the directory I'm finding: 

```
PS D:\home\SiteExtensions\letsencrypt> dir


    Directory: D:\home\SiteExtensions\letsencrypt


Mode                LastWriteTime     Length Name                              
----                -------------     ------ ----                              
d----          8/3/2017  12:06 AM            app_data                          
-a---          8/3/2017  12:06 AM       2410 letsencrypt.0.7.3.nupkg           
-a---          8/3/2017  12:06 AM        601 scmApplicationHost.xdt            
-a---          8/3/2017  12:06 AM        171 SiteExtensionSettings.json        
```

I tried it a couple times with the same result. Looking at the jobs dir, we find: 

```
PS D:\home\site\wwwroot\App_Data\jobs\continuous\letsencrypt(letsencrypt.siteextension.job)> dir


    Directory: D:\home\site\wwwroot\App_Data\jobs\continuous\letsencrypt(letsen
    crypt.siteextension.job)


Mode                LastWriteTime     Length Name                              
----                -------------     ------ ----                              
-a---          8/3/2017  12:06 AM          0 _._                 
```              

I'm guessing it's a simple pack error, especially with the name of the only file looking like part of a file mask. This did not happen on any previous version.

Time allowing I'll have a look through the source, but I thought I should throw this up here for now regardless. 

Thank you!

**Comment by sjkp** [comment]
It is a mistake it shouldnt have been pushed out yet, I was still doing testing. Oh well.

**Comment by sjkp** [comment]
I unlisted the bad version. You and the 13 others who have installed it have to uninstall and reinstall the old version for now. If the kudu portal keeps showing the 0.7.3 version, you might have to kill the process, as it caches the nuget feed.
