### ISSUE TITLE
0.7.4 version says "You do not have permission to view this directory or page."

### ISSUE THREAD

**Issue by justdmitry** [sjkp/letsencrypt-siteextension#157]
![firefox_2017-08-04_11-19-09](https://user-images.githubusercontent.com/3540597/28960321-c6de8d5a-7906-11e7-9417-3a247208bd55.png)

Version 0.7.4 for x86 is currently active in Azure/Kudu, after installation it doesn't open - returns "You do not have permission to view this directory or page." when navigating to https://_sitename_.scm.azurewebsites.net/letsencrypt/

**Comment by sjkp** [comment]
Wut it is not supposed be released so it is probably a broken package like #156 - I wonder what pushes my package.

**Comment by sjkp** [comment]
Please uninstall it and reinstall the old version. I think my AppVayor have started releasing the package, but it is not building it correctly.

**Comment by justdmitry** [comment]
It was able to perform "update", effectively downgrading to 0.6.17. Now works. Thank you.

**Comment by justdmitry** [comment]
Again, x86 version is `0.7.5` now. I guess you need to unlist it again...
