### ISSUE TITLE
letsencrypt.azure.core NuGet package mismatched architecture dependencies

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#159]
`letsencrypt.azure.core` depends on both `ACMESharp.PKI.Providers.OpenSslLib32` and `ACMESharp.PKI.Providers.OpenSslLib64` which means that whatever architecture you choose, you will always get a warning like the following:

> There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "ManagedOpenSsl64, Version=0.6.1.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by sjkp** [comment]
Please use the latest version, it doesn't have a dependency on OpenSsl https://www.nuget.org/packages/letsencrypt.azure.core/0.7.2-prerelease

**Comment by ohadschn** [comment]
Nice, any plans for a stable version?

**Comment by sjkp** [comment]
My time to work on it is a little bit on/off, but I'm hoping to get to something that you can rely on by the end of august.
