### ISSUE TITLE
letsencrypt:ClientSecret should be a connection string (rather than a regular app setting)

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#160]
It is a secret, and should be protected as such in the app settings.

**Comment by sjkp** [comment]
What level of protection does connection string provides over app settings, sorry for my ignorance, but to my knowledge they are both equally insecure. I'm aware that the azure portal on writes <Hidden for security reason> on connection strings, but they are visible to everyone with access when you click them. They are also accessible and readable from the kudu portal under environment settings. 

Not that it is a big deal to change, but I just don't see the value in it. I would much rather provide support for key vault or spend time on other features, unless the is a serious benefit security wise by using connection strings.

**Comment by ohadschn** [comment]
Yeah I was talking about that `<Hidden for security reasons>` thing. Don't know if there's anything more to it. Prioritizing other things (especially KeyVault support) sounds fair.
