### ISSUE TITLE
Request and Install Certificate

### ISSUE THREAD

**Issue by ahmadabdullah247** [sjkp/letsencrypt-siteextension#164]
Website is failing to install certificate, please guide what is this issue.
![screen shot 2017-08-21 at 11 31 48 am](https://user-images.githubusercontent.com/6478804/29506343-a3dd2ee0-8664-11e7-8f73-ab298a7cc047.png)

**Comment by sjkp** [comment]
Did you browse: 
https://acme-staging.api.letsencrypt.org/acme/authz/jNAmbLGLgY67JAH-K7yvC4mDZPHfaO7kz17K1gy3ULk 

It seems theres an dns issue.

**Comment by ahmadabdullah247** [comment]
I saw the error, but not sure how to resolve it.

**Comment by sjkp** [comment]
Tbh, it is a little outside my area of expertise. I would recommend that you ask on the letsencrypt support forums, as it strictly has nothing to do with the extension. 

But did you make a CName or an AName record for your domain that points to the azure web app? I cant seem to find that when I lookup your domain on https://mxtoolbox.com/SuperTool.aspx?action=dns%3agifylapse.com&run=toolpage#

**Comment by arche89** [comment]
After installation and configuration brand new WebApp I've got following error: (not sure if it should be separate issue)

<img width="1381" alt="przechwytywanie" src="https://user-images.githubusercontent.com/11596948/37237455-b1e28c72-2413-11e8-86a5-9a965bf79fea.PNG">

**Comment by sahgilbert** [comment]
@arche89 Did you manage to resolve this? If so, how did you fix the error? I have a different server error, which I am trying to understand if there is a link between the problems you had and the issue I am seeing. Thanks.

**Comment by sjkp** [comment]
@sahgilbert  make a new issue with the stack trace, and I can see if I can help. The above error  looks like a misconfiguration or that the service principal have insufficient rights to the resource group that the web app resides in.

**Comment by sahgilbert** [comment]
Thanks @sjkp Please see [#212](https://github.com/sjkp/letsencrypt-siteextension/issues/212)

**Comment by sjkp** [comment]
closing due to age. If you didn't find a solution please reopen with the latest details.
