### ISSUE TITLE
One or more app settings are different from the values entered, do you want to update the app settings?

### ISSUE THREAD

**Issue by minhSkoolbo** [sjkp/letsencrypt-siteextension#165]
Hi when I enter the details for the Let'sEncrypt extension on Azure. I got this error. I've use this same ClientId and Password successfully on another web app. But when i try to do the setting for this web app I have this error.
Does it mean I have to create one service principle for each web app separately?

> One or more app settings are different from the values entered, do you want to update the app settings?

> The ClientId registered under application settings 00000000-0000-0000-0000-000000000000 does not match the ClientId you entered here 2c870d4f-xxxxx-429a-a33a-xxxxxxx

Thanks.

**Comment by sjkp** [comment]
No you can use the same as much as you want. The error/warning you see is because the site extension tries to tell you that your app setting is different  00000000-0000-0000-0000-000000000000 from what you typed in the UI  2c870d4f-xxxxx-429a-a33a-xxxxxxx, and it then wants you to update the App setting, so that it can have access to it next time the autorenewal web jobs runs.

**Comment by minhSkoolbo** [comment]
Thank sjkp for replying. I still don't understand what app setting where should the application Id is from.
The ClientId and ClientSecret is 
"The ClientId registered under application settings 00000000-0000-0000-0000-000000000000"  is it support to be the key letsencrypt:ClientId under my webapp application settings? I don't actually see this setting anywhere in my Application Settings. 

I followed the tutorial below and successfully set itup for 1 site. Not sure why the same service principle's ClientId and ClientSecret doesn't work for another app.
https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/21872#.WaeElT4jGUk

**Comment by sjkp** [comment]
If you set the check mark in allow update app setting and go to next page the site extension will add the letsencrypt:ClientId appsetting for you with the value you typed in in the interface.
