### ISSUE TITLE
Seems to sometimes work, sometimes errors out.

### ISSUE THREAD

**Issue by Surenapetrosyan** [sjkp/letsencrypt-siteextension#169]
Hey, I'm running into this issue and I can't figure out what to do about it. 

The SSL certificate is for my azure web api project that's being consumed by another front-end application to serve data. 

Sometimes the SSL certificate works and sometimes it doesn't, both for mobile and desktop, Chrome, Firefox and IE. 

I checked my browsers SSL certificate on howsmyssl.com so I don't think that's the issue.

If it's working it will work for a few minutes, though its starting to look like it stops working when you stop going to the website for a while. Make a few requests and it starts working until you stop making requests again. Sometimes it's been a while and it works on the first request though, so it could just be coincidence. 

The error message is either: 
Failed to communicate with the secure server or This site can't provide a secure connection.

Any ideas?

**Comment by sjkp** [comment]
That sounds very strange, are you using multiple web front ends, either behind traffic manager or web site slots where you route a percentage of the traffic between them? Which plan are you on? If you are just using a single site, then this is not something I have experienced myself, and I would suggest that you open a ticket with MS, if you in anyway can find a way to reproduce it.

**Comment by Surenapetrosyan** [comment]
Well I have one vue.js front-end that's hosted on zeit.co/now and it consumes the API that has the SSL. The problem seems to have fixed itself though, no problems today.
