### ISSUE TITLE
When site root url is not mapped to wwwroot, ACME Server is not able to resolve the Challange/Answer File

### ISSUE THREAD

**Issue by mysim1** [sjkp/letsencrypt-siteextension#17]
Most azure websites are default deployed to the wwwroot folder. For my case we are using different Application mappings and folders. Therefore the Answer resolving process is unable to complete because Azure Letsencrypt writes the Answer file to the wwwroot folder. 

Suggestion 1: add an additional parameter to configuration screen to configure non-default local folder for the .wel-known folder deployment.

**Comment by mysim1** [comment]
Suggestion 2: read the IIS folder mapping and resolve the folder mapped to path '/' before writing the challange/answer files.

**Comment by sjkp** [comment]
I will probably go with option 1. It is the easiest and will be sure to work solution.

**Comment by sjkp** [comment]
I have added an extra app setting `letsencrypt:WebRootPath` if you update to version 0.3.1, that you can try with, bare in mind I have not tested this - so you have to play around with it to get the path correct, e.g. use the kudu console

**Comment by stiucsib86** [comment]
Is the path hardcoded?
![screen shot 2016-02-05 at 10 42 17 am](https://cloud.githubusercontent.com/assets/74789/12836602/71ca7f6e-cbf5-11e5-9e27-a1e216900ed6.png)

**Comment by mysim1** [comment]
IT might be thw Azure application spn step that is skipped or gone wrong

**Comment by sjkp** [comment]
@stiucsib86 yes you are right, if you override in app settings it you should specific the full path yourself.

**Comment by sjkp** [comment]
@stiucsib86  The fix is up in the new version 0.3.2

**Comment by stiucsib86** [comment]
Awesome! Will try it out and let you know whether its working fine.

**Comment by stiucsib86** [comment]
Successfully installed! :D

**Comment by mburumaxwell** [comment]
Sorry to reopen this but I though it would help someone with a similar situation as mine now or in the future. I had a Ghost blog running on Azure with iisnode. To get the `{your-domain}/.well-known/acme-challenge/*` routes mapped to the right place, I needed a change in the web.config file and not the `letencrypt:WebRootPath` configuration value. I replaced the original rewrite rule for static content in the public folder to this below:

```xml
<rule name="AcmeContent">
     <match url=".well-known/acme-challenge/*" />
     <action type="Rewrite" url="{REQUEST_URI}"/>
</rule>
<rule name="StaticContent">
     <match url="public/*" />
     <action type="Rewrite" url="{REQUEST_URI}"/>
 </rule>
```

If it pleases you, you may add this to the troubleshooting document.

**Comment by sjkp** [comment]
thanks @mburumaxwell will add it to the troubleshoot guide

**Comment by mysim1** [comment]
Awesome! I had no time to deal with this corner case. So many thanks
sharing this.


 Hartelijke groet,
 Hans van den Akker
 Founding CEO

*Adres*
Overhoeksplein 2 / Lab 0.02
1031 KS Amsterdam

+31 6 390 31 386
www.bizboard.nl
www.facebook.com/bizboard
https://www.linkedin.com/company/bizboard


2016-03-02 18:02 GMT+01:00 Maxwell Weru <notifications@github.com>:

**Comment by leolorenzoluis** [comment]
@mburumaxwell Hi, I tried following your solution but it looks like it's still not serving the folder path. Do you know why?

**Comment by leolorenzoluis** [comment]
ping

**Comment by leolorenzoluis** [comment]
@sjkp Okay, so if I understand correctly, does the extension has its own web app that tries to communicate with lets encrypt? So if it's hosted on Azure App Service, there are 2 instances of web apps running. One is for this extension, and the other is my own web app?

As far as I know, there should only be one web.config for a web app that's running? Not sure if partial web configs are allowed. 

Or does it mean that since the extension writes at the \wwwroot, I just have to modify my existing web.config and update it with your rewrite so that it can serve those files?

**Comment by lucaluca** [comment]
@mburumaxwell This worked great for me, but I had to add `stopProcessing="true"` first. Thanks!
