### ISSUE TITLE
Kudu Gallery display 3 let's encrypt extension

### ISSUE THREAD

**Issue by tsugawa** [sjkp/letsencrypt-siteextension#170]
Hi, 

Is it right? Is there version v0.7.5 x64?

![image](https://user-images.githubusercontent.com/8302404/31199966-7be2171e-a92f-11e7-9ce8-7822d10f224a.png)

Tks.

**Comment by sjkp** [comment]
It was a mistake that one of them wasn't renamed. I will fix it with the next release. 

But you can click the small (i) icon to see the id / package name, the two that are named the same is

- letsencrypt - contains everything
- letsencrypt.webapponly - contains no web jobs for renewals, so you must have som other way to do that if you install that 

![image](https://user-images.githubusercontent.com/3397744/31578456-d9674036-b121-11e7-9da1-c4a2a4448db5.png)
