### ISSUE TITLE
New letsencrypt.azure.core version?

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#177]
Congrats on the new release!

Any plans for a corresponding [letsencrypt.azure.core](https://www.nuget.org/packages/letsencrypt.azure.core) update?

**Comment by sjkp** [comment]
Yes, I have released it now. There might be some breaking changes, haven't really been keeping track.

**Comment by ohadschn** [comment]
Thanks!

Still pre-release I see... you are a careful one.
