### ISSUE TITLE
Last step is forbidden?

### ISSUE THREAD

**Issue by KennethJakobsen** [sjkp/letsencrypt-siteextension#180]
Hi i'm able to go thru the entire guide but when I get to the last step (Request and install) i get the following error:

![image](https://user-images.githubusercontent.com/17765492/33117131-98d06908-cf67-11e7-8fe5-60d63852d26c.png)

**Comment by sjkp** [comment]
This happens when the service principals fails to install the received certificate into the ServicePlanResourceGroup. 

Are you using different resource groups for the app service plan and the web app? If so did you ensure that the service principal, have contribute access to both resource groups?

**Comment by KennethJakobsen** [comment]
No same resource group but i may be having some issues figuring out the correct ids especially tenant and clientId.

Is it correct that the tenant id is found below my username in Azure portal? in my case kennethjakobsenyahoo.onmicrosoft.com

Is the client id (App registration) application ID?

**Comment by KennethJakobsen** [comment]
Thanks for the help seems like i set up the principal on the webapp instead of Resource group

**Comment by sjkp** [comment]
Ok, that makes sense. Because you should have got the error a lot earlier in the process if the service principal was not setup correctly.
