### ISSUE TITLE
The Lets Encrypt ACME server was probably unable to reach

### ISSUE THREAD

**Issue by Soulskater** [sjkp/letsencrypt-siteextension#182]
Could you help me figuring out what is the problem with installing letsencrypt?
https://acme-v01.api.letsencrypt.org/acme/authz/PiRciQtLTBpRfK8Vk_04aFQp9vmsAMmDf76eWUvpkeQ

**Comment by sjkp** [comment]
Your sites redirects all traffic to https, that is not going to work for the lets encrypt challenge. Request to /.well-known/acme-challenge must be served over http.

**Comment by Soulskater** [comment]
Yes you're right, i switched off httpsonly, after that still got the error, but finally i get it work by changing the site root back to site\wwwroot, i guess it needs for relative path or something

**Comment by IAMtheIAM** [comment]
I had the exact same issue. Installed redirect to HTTPS before installing SSL so let's encrypt was not able to read the `./well-known` file.

Then I had to accommodate for the fact that let's encrypt installs its the file to `site/wwwroot/.well-known` where as my app root is actually `site/wwwroot/wwwroot/.well-known`

I handled this in my nodejs express app like so:

```ts
    /**
     * Allow Let's Encrypt to verirfy the domain and automatically renew SSL certs
     */
    app.use(exclude('/.well-known*', router));

    // Need to go up to root of azure for Let's Encrypt verification to work, at site/wwwroot (not site/wwwroot/wwwroot)
    router.get('/.well-known*', function(req, res, next) {
        res.sendFile(req.originalUrl, { root: path.join(__dirname, '../../../') });
    });
```

Work's perfectly now, thanks!
