### ISSUE TITLE
How does the new no webjobs version work?

### ISSUE THREAD

**Issue by tghamm** [sjkp/letsencrypt-siteextension#185]
I was setting up a new site and saw that there's a new version that doesn't require webjobs, which is really cool.  But I was wondering, how does the cert get renewed then?  I couldn't seem to find any documentation on it.

Thanks for this project, it's been a huge help to us!

**Comment by DavidChenware** [comment]
The description in the site extension info panel says that custom requests need to be sent to the API. It doesn't seem like it is an automated solution by itself.

**Comment by sjkp** [comment]
I wrote a blog post about you how you can use azure function to automate calling the API. 
http://wp.sjkp.dk/lets-encrypt-on-azure-web-apps-using-a-function-app-for-automated-renewal/ 

But yes @DavidChenware is right it is not a fully automated you need to do some more yourself.
