### ISSUE TITLE
webapp extensions x86 and x64

### ISSUE THREAD

**Issue by modemgeek** [sjkp/letsencrypt-siteextension#187]
the options for the webapp extension used to say x86 and x64.  I now notice that one doesn't have one and is version 0.8.5 and the x64 version is 0.6.17.

Is the 0.8.5 version only for x86?  Is there any difference between this version and the 0.6.17?

**Comment by sjkp** [comment]
Because you can use 0.8.5 for both. So I'm not updating the x64 any more.

**Comment by modemgeek** [comment]
Thanks for the explanation. If we have the x74 installed, do we have to
reissue all the certificate when we install the newer extension?

**Comment by sjkp** [comment]
You shouldn't have to. There is no difference in the certificates. If you install the new version the settings should just carry over and work as before.

**Comment by modemgeek** [comment]
So I can just install the newer version and remove the x64 version?  Does it make any difference in the order that I do?

**Comment by sjkp** [comment]
You should uninstall the old one first.
