### ISSUE TITLE
ACME TLS-SNI Vulnerability - What's the impact?

### ISSUE THREAD

**Issue by tghamm** [sjkp/letsencrypt-siteextension#189]
Will this be an issue for the azure let's encrypt bot?

[https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188](https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188)

Thanks!

**Comment by drasive** [comment]
Your link is broken: https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188

**Comment by sjkp** [comment]
There is no impact, the extension only supports http or dns validation. So nothing needs to be done afaik.
