### ISSUE TITLE
Web job prevent App service from working

### ISSUE THREAD

**Issue by mehmetilker** [sjkp/letsencrypt-siteextension#193]
When I look at logs I see web job is working everyday.
Few times in a week my app service stop responding to requests.
When I look at the logs I see it happens in the same time with web job action.
CPU goes to around %100 in App service and according to logs web job took 18 seconds. 

Functions.Cleanup (02/11/2018 06:32:3 ...) | Success | 7 hours ago (8 s running time)
Functions.RenewCertificate (02/11/2018 06:32:3 ...) | Success | 7 hours ago (7 s running time)
Functions.AddCertificate (02/11/2018 06:32:3 ...) | Success | 7 hours ago (3 s running time)

 
If letsencrypt:RenewXNumberOfDaysBeforeExpiration setting was working as expected there should be only one log in 3 months.
Or am I wrong, should I set it manually in my config ?

**Comment by sjkp** [comment]
The web jobs runs on startup, so if for some reason your web app recycles, they will run again. So you should investigate what is causing the web app to recycle. 

I assume that you have always on enabled.

**Comment by mehmetilker** [comment]
Always on enabled but you are right. When I have checked event longs I see "Application 'MACHINE/WEBROOT/APPHOST/xxx' started process '6824' successfully and is listening on port '3145'." logs.
So you are right.

And this problem made me realize different problem caused by platform... It is common problem I think.
Around 2/12/2018 12:36:58 PM (UTC), On Instance RD0003FF4160DF, Your application was recycled due to an intermittent Azure infrastructure issue while accessing remote file storage....

Thank you for your reply.
