### ISSUE TITLE
"Request and install certificate" fails for azure web app when https redirect in web.config is present

### ISSUE THREAD

**Issue by harald-d** [sjkp/letsencrypt-siteextension#195]
The following code handles http to https redirection for one of my webapps. When I click "Request and Install certificate" to finish the certificate installation of my azure web app, it fails because it can't access the link via http..

`   <rule name="Redirect to HTTPS" stopProcessing="true">
          <match url="(.*)" />
          <conditions>
            <add input="{HTTPS}" pattern="^OFF$" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" redirectType="SeeOther" />
      </rule>`

Is there a known way to have an intact http to https redirect, while the certificate issuing also works ?

Thanks in advance !

**Comment by sjkp** [comment]
Disable http redirect for the /.well-known/acme-challenge folder of your web app.

**Comment by harald-d** [comment]
Thx, that worked !
