### ISSUE TITLE
Extension doesnt work with EndpointSuffix=core.windows.net - how to cope ?

### ISSUE THREAD

**Issue by harald-d** [sjkp/letsencrypt-siteextension#197]
In your wiki for installing on azure web apps you mention this:

> Besure that the connection string doesn't end with EndpointSuffix=core.windows.net as the extension will not work then.

If i copy my connection string from the blob storage they end with exactly this - 
How can / should I change that, and how could I test if its working with the given connection string ?

Thanks in advance and best regards,
Harald

**Comment by harald-d** [comment]
@sjkp I would be glad if you can give me a hint how to solve this :)

**Comment by sjkp** [comment]
That information from the wiki is outdated, if you installed the latest version 0.8.5 of the extension, you can include it without problems. 

Thanks for letting me know I will update wiki .

**Comment by harald-d** [comment]
Great, thanks for the update !
