### ISSUE TITLE
Support non-ascii domain names

### ISSUE THREAD

**Issue by asapostolov** [sjkp/letsencrypt-siteextension#199]
I have [a case](https://github.com/ohadschn/letsencrypt-webapp-renewer/issues/41) in which I need to configure a domain name with non-ascii characters to renew its SSL certificate through Let's Encrypt. Currently there is an error when I try to do it with this extension.

The desired behavior is this:
When sending the domain name to the Let's Encrypt server, the domain should be properly encoded with punycode(which currently is not and results in an error(`Invalid character in DNS name`) from the server). When the domain name is used to match Azure's configured domains, the domain name should be used 'as-is' - with the non-ascii characters (because that's the only way that Azure supports non-ascii character containing domains).

**Comment by asapostolov** [comment]
If there is any way to speed up this issue, I'd be grateful.

If you don't have time to do it right now, I'm open to changing the code myself if you point me in the right direction.

**Comment by alvipeo** [comment]
Here's the stack trace when trying to use punycode domain names:

> [WebException: The remote server returned an error: (400) Bad Request.]
>    System.Net.HttpWebRequest.GetResponse() +1695
>    ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) in J:\projects\letsencrypt-siteextension\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:708
> 
> [AcmeWebException: Unexpected error
>  +Response from server:
> 	+ Code: BadRequest
> 	+ Content: {
>   "type": "urn:acme:error:malformed",
>   "detail": "Error creating new authz :: Invalid character in DNS name",
>   "status": 400
> }]
>    ACMESharp.AcmeClient.AuthorizeIdentifier(String dnsIdentifier) in J:\projects\letsencrypt-siteextension\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:267
>    LetsEncrypt.Azure.Core.Services.<Authorize>d__5.MoveNext() in J:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\BaseHttpAuthorizationChallengeProvider.cs:62
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.Azure.Core.Services.<RequestCertificate>d__5.MoveNext() in J:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:41
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.Azure.Core.<RequestInternalAsync>d__12.MoveNext() in J:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:173
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.Azure.Core.<RequestAndInstallInternalAsync>d__13.MoveNext() in J:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:186
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.SiteExtension.Controllers.<Install>d__7.MoveNext() +816
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +92
>    System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +385
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +30
>    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
>    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
>    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
>    System.Web.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar) +212
>    System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +166

**Comment by MTrachsel** [comment]
I'm having the same issue as well. If it hasn't been done yet I might try to fix it and send a pull request.

**Comment by asapostolov** [comment]
I've worked around this issue by using the encoded domain names e.g. xn----8sba9bojn.com to run the task. When I do that there is an exception in the process of assigning the certificates, but the certificates get issued correctly and are visible in Azure. When the task completes I switch the old ones with the new ones manually from the admin interface of Azure and they work. After 3 months I repeat the process.

It's good enough for me now. As a further workaround one could probably create a power-shell script to switch to the new ones automatically but maybe at that point it's better to do the actual fix of letsencrypt-siteextension and make a pull request.

**Comment by alvipeo** [comment]
I just did that manually, it's not that difficult:

1. On Windows 10, Open Ubuntu (Linux subsystem)
2. Go to https://certbot.eff.org/lets-encrypt/ubuntuxenial-other and install certbot (in Ubuntu)
3. Run: `sudo certbot certonly --manual -preferred-challenge dns -d <punycode-domain-name>`
4. Convert to .pfx (from .pem): `sudo openssl pkcs12 -export -out azure.pfx -inkey /etc/letsencrypt/live/<punycode-domain-name>/privkey.pem -in /etc/letsencrypt/live/<punycode-domain-name>/fullchain.pem`

Then go install that cert to Azure. Done.

**Comment by MTrachsel** [comment]
Hi Apostol

Can you help me out here. Where exactly in azure did you enter the encoded Domain? I tried via Portal and Azure Powershell but azure doesn’t accept the encoded Version at all…
Thanks!

Cheers
Markus

________________________________

**Comment by sjkp** [comment]
I have released a new version 0.8.7 that enable support for this. Please let me know if you encounter any issues, azure seems to handle non-ascii letters in domain names without any encoding, so it was only letsencrypt that required punycodes.

**Comment by alvipeo** [comment]
Thank you!

**Comment by MTrachsel** [comment]
Thanks @sjkp I'll have to set it up again. But it sounds great! :)

**Comment by MTrachsel** [comment]
Hi @sjkp 
I finally got around to trying your new Version. I'm trying to add "bärfoods.ch" and am getting the following error:
The Lets Encrypt ACME server was probably unable to reach http://xn--brfoods-5wa.ch/.well-known/acme-challenge/zRcvUGgB9YNXReTeg1wyFuiuHWNhvhR3VYNn5XxwjnU view error report from Lets Encrypt at https://acme-v01.api.letsencrypt.org/acme/authz/eCe0WlBB4PhiFefRF2cYpWHNGKWtkQzZw9C9nKDaB2Y for more information

Any ideas? Somewhere the name is translated to punycode it seems. 

Best Regards 
Markus

**Comment by Viir** [comment]
> @sjkp could you please release a corresponding version of `LetsEncrypt.Azure.Core`? (I can only see 0.8.5)

@ohadschn There is now a version `0.9.3` on nuget: https://www.nuget.org/packages/letsencrypt.azure.core/0.9.3

Thank you @sjkp for the update 👍
