### ISSUE TITLE
Move Site Extension to nuget.org

### ISSUE THREAD

**Issue by davidebbo** [sjkp/letsencrypt-siteextension#200]
Please see https://github.com/Azure/app-service-announcements/issues/87

**Important**: you need to do this before June 1st 2018. Please let me know if you have any questions.

Thanks!

**Comment by sjkp** [comment]
Thanks for the heads up - might have missed that otherwise.

**Comment by davidebbo** [comment]
Sure thing.

You also own https://www.siteextensions.net/packages/livesettings/, but the project link there looks broken: https://github.com/sjkp/sjkp
