### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by trevski** [sjkp/letsencrypt-siteextension#209]
I am getting the following and I am sure I have everything correct, any clues ?

Microsoft.Rest.Azure.CloudException: The client '2c03e3cd-63bf-4d7d-ae1e-ae362d714221' with object id '2c03e3cd-63bf-4d7d-ae1e-ae362d714221' does not have authorization to perform action 'Microsoft.Web/sites/read' over scope '/subscriptions/e2c81119-8d02-4376-9414-283a155cde60/resourceGroups/vegfundforum/providers/Microsoft.Web/sites/vegfundforum'. at Microsoft.Azure.Management.WebSites.WebAppsOperations.

**Comment by sjkp** [comment]
Have you granted the service principal you created in Azure AD access to the resource group vegfundforum it needs contribute permission.

**Comment by trevski** [comment]
Just to be clear on terminology, as it all seems to be different in the Azure UI "service principle" are the credentials created in "App Registrations", the client ID is Application ID of the "App Registration" and the "client key" is the "Password" created therein ? 

Within the "Resource Group" that the "app registration" is added to the "Access Control" section.

OK I have found the problem, I added permissions to the App itself rather than the service principle as I had given them the same names.

Looks like azure has updated the UI since the docs were written,

**Comment by trevski** [comment]
I have it all working now thanks.

**Comment by MorayM** [comment]
@trevski I'm having the same problem, can you confirm which ID you entered for the ClientID? Is it the Application ID or the Object ID? Whichever one I use gives the same error. I have made the application service principal a Contributor to my resource group.

**Comment by trevski** [comment]
Sorry this is months ago I set this up. I can't recall.

**Comment by MorayM** [comment]
@trevski No worries, I thought that might be the case!
