### ISSUE TITLE
An existing connection was forcibly closed by the remote host 

### ISSUE THREAD

**Issue by alvipeo** [sjkp/letsencrypt-siteextension#214]
On the 'Request and Install Certificate' I selected my custom domain and provided email => click Next => error:

> [SocketException (0x2746): An existing connection was forcibly closed by the remote host]
>    System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult) +8433419
>    System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult) +45
> 
> [IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.]
>    System.Net.TlsStream.EndWrite(IAsyncResult asyncResult) +294
>    System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar) +149
> 
> [WebException: The underlying connection was closed: An unexpected error occurred on a send.]
>    System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +729
>    System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +77
> 
> [HttpRequestException: An error occurred while sending the request.]
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.SiteExtension.Core.Services.<Authorize>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\BaseAuthorizationChannelgeProvider.cs:86
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    LetsEncrypt.SiteExtension.Core.Services.<Authorize>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\BaseAuthorizationChannelgeProvider.cs:131
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.SiteExtension.Core.Services.<RequestCertificate>d__5.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:39
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.SiteExtension.Core.<RequestAndInstallInternalAsync>d__10.MoveNext() in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:150
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    LetsEncrypt.SiteExtension.Controllers.<Install>d__7.MoveNext() +801
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
>    System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +92
>    System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +385
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +30
>    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
>    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
>    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
>    System.Web.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar) +212
>    System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +166
>

**Comment by sjkp** [comment]
It doesnt look like you are running the latest version. 

It fails at trying to validate that the challenge file is accessible in the /.well-known/ directory can you see if the file is there and that you can browse it on your http web site url

**Comment by alvipeo** [comment]
how am I supposed to know which one is the latest?

![image](https://user-images.githubusercontent.com/1990415/40283619-cf0ce78a-5c89-11e8-8f16-796781e85e02.png)

**Comment by alvipeo** [comment]
I used x64

**Comment by sjkp** [comment]
Yes the portal.azure.com UI is not very good :/ can you install the 0.8.6 from the https://[your-site>.scm.azurewebsites.net/SiteExtensions/?#gallery  ? You have to uninstall the x64 bit version first. There is no longer a need for a seperate 64bit version.

**Comment by alvipeo** [comment]
I just run this https://github.com/hansenms/LetsEncryptWebApp and it worked for me. I'll try the extension next time.

please remove old versions from the gallery. it's a bit confusing.

Thank you! I'll try the extension, promise! :)

**Comment by sjkp** [comment]
@alvipeo the old versions are removed now. If you encounter errors in the future feel free to open a new issue.
