### ISSUE TITLE
Add Site Extension installation instructions

### ISSUE THREAD

**Issue by mor10** [sjkp/letsencrypt-siteextension#215]
On the How to install page, the "Install the Let's Encrypt Site Extension" section is missing. Since the extension is no longer listed, it can't be installed through the Site Extensions gallery. A basic primer on how to do it manually would be appreciated.

**Comment by sjkp** [comment]
Actually it should still be in the kudu portal too, but it is a bug I already report to MS: https://github.com/Azure/app-service-announcements-discussions/issues/34

**Comment by sjkp** [comment]
I have added it now.
