### ISSUE TITLE
Monthly Add vs Daily Renew

### ISSUE THREAD

**Issue by MisinformedDNA** [sjkp/letsencrypt-siteextension#216]
I'm new to Let's Encrypt, but I'm confused by what I read and what I see here. I thought we only had to add a certificate once, instead of monthly. Additionally, renewing daily meets the criteria of renewing every 90 days. But won't it also it the rate limit?

Like I said, I'm new. Can you clarify things for me?

**Comment by sjkp** [comment]
If you have installed the extension with the web job, then the web job will take care of renewing the certificate 21 days (the default, can be changed) before it expires, it expires after 90 days. 

It is correct that the web job triggers every day, but it doesn't do anything unless you are within the 21 day window of the certificate expiring. This design is basically to ensure, that if something is preventing the web job from running, you should have a fair amount of extra time to either fix the problem or the web job will try again the next day.
