### ISSUE TITLE
No custom domain detected on app service with 9 custom domains

### ISSUE THREAD

**Issue by josundt** [sjkp/letsencrypt-siteextension#219]
On the second screen of the site extension configuration wizard, I get the message:

_"At least one custom domain must be registed with the web application before you can request any Let's Encrypt SSL certificate for it. Read here how to setup custom domain names. Ensure that DNS settings are correct before you continue. "_

There are 9 custom domains registered for my app service that all work with http, **and these are all listed on the same page right below**! 

I am 98% certain that I have done everything else correctly, following the recipe from https://www.hanselman.com/blog/SecuringAnAzureAppServiceWebsiteUnderSSLInMinutesWithLetsEncrypt.aspx

What could be the case?
Is there a bug in the site extension for app services with a large number of custom domains?
Could it be a problem that some of the custom domains are subdomains of the same domain?

**Comment by josundt** [comment]
Sorry, my mistake, closing the issue

**Comment by talloula** [comment]
@josundt can you please post what you did to get it working? 
I'm in the same boat!

Thanks.

**Comment by talloula** [comment]
The error was not an issue, I was able to continue by clicking next and it didn't cause any problems as far as I can tell, everything worked, so it must be a false positive.
