### ISSUE TITLE
Web publishing a project with "remove additional files at destination" deletes webjob

### ISSUE THREAD

**Issue by chadwackerman** [sjkp/letsencrypt-siteextension#22]
Publishing an MVC5 project with this option set deleted the letsencrypt webjob. Presumably "Exclude files from the App_Data" folder would have prevented this, but sometimes you get into issues that require a clean push. 

Preventing this may be difficult. But a warning in the documentation and a recovery option that recreates the webjob would be great.

**Comment by sjkp** [comment]
Thanks for the heads up. I will update the docs.

**Comment by ohadschn** [comment]
This would be resolved if the following was implemented: https://github.com/sjkp/letsencrypt-siteextension/issues/43#issuecomment-289228326, by simply creating a dedicated web app for LetsEncrypt renewals.

**Comment by ohadschn** [comment]
Isn't this a duplicate of https://github.com/sjkp/letsencrypt-siteextension/issues/22?

**Comment by sjkp** [comment]
With version 0.8.5 there is now API support and there is a extension without web jobs that can be used together with the API that can be used to prevent problems like this. 

I can't do more to prevent this unfortunately, so I'm closing this issue.
