### ISSUE TITLE
Site extension not in list of available extensions

### ISSUE THREAD

**Issue by rwaal** [sjkp/letsencrypt-siteextension#222]
I'm trying to install the Azure Let's Encrypt site extension on an Azure App Service (aka web app). However, it's not there when I look in the list of available site extensions. That's either through Kudu, or through the 'regular' Azure portal. Even when I try to install through an ARM template, it gives me back weird errors. 

I suspect that it has something to do that the web app lives inside an Azure Cloud Service Provider (CSP) subscription. Perhaps the offer of site extensions is different compared to pay-as-you-go or EA subscriptions. 

Are you aware that the extension is not available in CSP subscriptions? Why is that? And is there any other way to use the extension, perhaps through a manual installation?

Thanks in advance!!

**Comment by sjkp** [comment]
I have not tried it in a CSP subscription, but I will double check, I believe it should just work, but your never know.

**Comment by sjkp** [comment]
I just tried on one of our CSP subscriptions, I can't reproduce it. It show up just like it should. 
Can you try on a different web app? 

An alternative way to get the lets-encrypt cert is to use @ohadschn web job which is a C# solution without any need for installing site extensions https://github.com/ohadschn/letsencrypt-webapp-renewer

**Comment by rwaal** [comment]
Now this is strange.... I created a new Web App, and now the site extension is available for installation. The only difference is that the initial Web App was created through an ARM template. And the new Web App is created through the Azure portal. Perhaps something funny with API versions or something...

In any case, this solves the problem. Sorry for bothering you with such a trivial question. Many thanks for your help Simon!!

**Comment by sjkp** [comment]
@rwaal no problem, happy to help.
