### ISSUE TITLE
Error "No route registered for '/letsencrypt/'" with recent Functions App

### ISSUE THREAD

**Issue by ChristianWeyer** [sjkp/letsencrypt-siteextension#223]
I created two new Function Apps and get this error for both of them:

`"No route registered for '/letsencrypt/'"`
E.g. https://xtreme-serverless-functions.scm.azurewebsites.net/letsencrypt/

Any idea what could be wrong?

**Comment by ChristianWeyer** [comment]
Sorry for the confusion ;-)

**Comment by TastesLikeTurkey** [comment]
What was the solution here? I'm hitting the same issue.

**Comment by sjkp** [comment]
I will update the docs soon, but I think you can't name the proxy and route the same.

**Comment by sudsy** [comment]
I just had this error on an azure app service and found that a restart of the app service fixed it.

**Comment by JustMaier** [comment]
@sjkp Do you think it's reasonable to add the instructions from @sudsy to the README install guide?

**Comment by AlexJPawlak** [comment]
Still an issue, thanks for comment and solution

**Comment by goh-chunlin** [comment]
> I just had this error on an azure app service and found that a restart of the app service fixed it. Turns out it only seems to work if I "Restart Site" within Kudu > Extensions

I just tried with Restart button at the Overview section of the web app on Azure Portal. It works too.
