### ISSUE TITLE
Issue during the Initial setup

### ISSUE THREAD

**Issue by TheWilhelm** [sjkp/letsencrypt-siteextension#224]
Hello i followed the installation guide of the wiki.
however during the "Configure the Site Extension" step after inserting all data and fixing the Permission.
i got This Null Reference Exception:
`System.NullReferenceException: Object reference not set to an instance of an object. at LetsEncrypt.Azure.Core.SiteSlotExtensions.UpdateSiteOrSlotAppSettings(IWebAppsOperations sites, String resourceGroupName, String webAppName, String siteSlotName, StringDictionary settings) in J:\projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\SiteSlotExtensions.cs:line 45 at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model)`

The Current setup is: i have a slot with the Extension installed.
The Principal is setup and has the Right permissions(as the errors it initial had have cleared).
i waited some time just in case that azure took a bit longer to do stuff in background.
still getting the null reference exception.

**Comment by sjkp** [comment]
There was a bug if you had never created any web app settings for the slot, that would cause this exception. The latest release 0.8.7 fixes it.
