### ISSUE TITLE
Multiple App Plan Instances

### ISSUE THREAD

**Issue by bannypotter** [sjkp/letsencrypt-siteextension#225]
Just wondering what happens if I have the extension installed on a site part of an app plan which has multiple instances? I'm assuming that it will just work as the site scales? I need to make sure that I can run at least 2 instances to maintain availability/redundancy.

Specifically thinking about webjob renews and whether it's running as a singleton etc..

**Comment by sjkp** [comment]
The web job runs a singletons, to avoid having multiple certificate request going off at the same time. 

Besides that it should just work, but it is not something that I have tested thoroughly, so if you experience any issues feel free to post them.
