### ISSUE TITLE
extension does not work if root folder is empty

### ISSUE THREAD

**Issue by avs099** [sjkp/letsencrypt-siteextension#226]
in my app service, I did not want make "/" URL available - so I pointed it to "site\empty" folder (and there was nothing in that folder). And then I created an app in App Settings and pointed "/my-app" to "site\wwwroot" folder. In this setup, after I launched letsencrypt extension, I get

> No route registered for '/letsencrypt/'

message for the https://my-ap.scm.azurewebsites.net/letsencrypt/ URL.

However, if I changed root app's folder to "site\wwwroot" - things started to work.

**Comment by sjkp** [comment]
Hmm, I'm afraid this is not something that I can fix. The route gets registered when the extension gets installed in scm site by the Kudu portal. And you did try to restart the kudu portal after installation?
