### ISSUE TITLE
Extension was unlisted from gallery

### ISSUE THREAD

**Issue by xperiandri** [sjkp/letsencrypt-siteextension#231]
Will it be relisted again?

**Comment by xperiandri** [comment]
Ah, I see it is now built-in
https://feedback.azure.com/forums/169385-web-apps-formerly-websites/suggestions/6737285-add-support-for-free-ssl-certs-like-those-from-let

**Comment by sjkp** [comment]
I should not be unlisted, I just looked it up, and it is still there. 
![image](https://user-images.githubusercontent.com/3397744/43489438-521b032a-951d-11e8-988b-71f6b3441cc8.png)

Which region is it not showing up for you?

**Comment by xperiandri** [comment]
South Central US

![image](https://user-images.githubusercontent.com/2365592/43508165-d180b664-9577-11e8-8672-19bb96ffd662.png)

**Comment by xperiandri** [comment]
It is no longer available at https://www.siteextensions.net/profiles/sjkp

**Comment by sjkp** [comment]
I have unlisted it from the old siteextensions.net site, as requested from MS as they are deprecating it
#200

**Comment by sjkp** [comment]
If you have the web app setting SCM_SITEEXTENSIONS_FEED_URL set, which you might have if you have been using my arm templates, then please remove that, so it default to nuget.org.
