### ISSUE TITLE
Server Error in '/letsencrypt' Application

### ISSUE THREAD

**Issue by emicarito** [sjkp/letsencrypt-siteextension#237]
Hi,

When I try to create a new certificate, the website shows me an error page.

![image](https://user-images.githubusercontent.com/18602654/43926989-a4f32f48-9bf1-11e8-87e5-301bb645cd05.png)

And the certificate is never created.

**Comment by slamotte** [comment]
Check the first line of the error message, I had something similar before.

**Comment by sjkp** [comment]
Lets Encrypt servers need to be able to browse your challenge file. 
You can see the detail error report in the url posted in the exception https://acme-v01.api.letsencrypt.org/acme/authz/mu_KlX8oDm26QHQ9PtFUgxD8AiWccRGHyPr5b2AjopI

If i try to browse the challenge URL for your web site, for the run where it failed: http://sinapsis.nuestraflota.com/.well-known/acme-challenge/eqI2PJDU45LBSw798rURA9-TO0upG28e8NPmVYqvHwM 

I see two immediate problems.
1. I am redirect to HTTPS (the challenge file must be accessible over http)
2. I am redirect to your login page, the challenge URL should return the content of challenge file as plain text
