### ISSUE TITLE
Getting confusing error

### ISSUE THREAD

**Issue by LCichanowiczPMG** [sjkp/letsencrypt-siteextension#244]
I am trying to get a cert for a .bank domain name.  Modern browsers know that .bank requires SSL, so to see the .well-known/acme-challenge, I just use IE or Fiddler, and the response looks fine.

The error report also states:
`DNS problem: SERVFAIL looking up A for mydomain.tld`

However, I see an A record:
https://mxtoolbox.com/SuperTool.aspx

[Edit]
I found two tools to help pinpoint the issue:

1. https://dnssec-analyzer.verisignlabs.com/

2. http://dnsviz.net/

If these don't pass for a domain, it's doubtful that Let's Encrypt will issue a cert.

**Comment by sjkp** [comment]
I don't have access to any bank TLD, so unfortunately I cannot help with this one.
