### ISSUE TITLE
WebJob Renew generates an new Certificate.

### ISSUE THREAD

**Issue by treinsberg** [sjkp/letsencrypt-siteextension#245]
Hi,

2 month ago I added the Azure Letsencrypt Extension on a new Website. The Certificate was generated and the WebJobs were there. Today the the Webjobs did a Certificate Renew. But after this I have the old Certificate and the new Certiface in the Azure Certificate List. The new added Certificate was also attached to the Domains, but now there ist an unused Certifacte that expires in 30 days.
Did I somthing wrong?

Thank for help.

**Comment by modemgeek** [comment]
as far as I know this is normal behavior.  we wrote a powershell script that goes back and deletes the older certificates.

**Comment by xt0rted** [comment]
There's a task that cleans up expired certificates. It might not remove the old certificate right away but it should once it's expired.

https://github.com/sjkp/letsencrypt-siteextension/blob/94ec784e208e6e9e96cc878b4f43803b974f8331/LetsEncrypt.SiteExtension.WebJob/Functions.cs#L70-L75

https://github.com/sjkp/letsencrypt-siteextension/blob/94ec784e208e6e9e96cc878b4f43803b974f8331/LetsEncrypt.SiteExtension.Core/Services/WebAppCertificateService.cs#L94

**Comment by treinsberg** [comment]
Ok, thats right. When the certificate is expired now, it was automaticly removed by the WebJob. Thanks for your help.
