### ISSUE TITLE
Upgrade from Azure Let's Encrypt (x64) to Azure Let's Encrypt

### ISSUE THREAD

**Issue by robrich** [sjkp/letsencrypt-siteextension#253]
My site currently has Azure Let's Encrypt (x64) v0.6.17, and I see Azure Let's Encrypt 0.8.7 is available in the gallery.  How do I upgrade to this new verson?  Must I uninstall the old plug-in and install the new one?  Will I lose my cert or appsettings as I do this?

**Comment by sjkp** [comment]
You can just uninstall. And reinstall. It shouldn't damage your site. I recommend running the manual install process once you are on the new version, just to be sure everything still works.

**Comment by robrich** [comment]
Apologies for unearthing an old issue.  My experience has been uninstalling the x64 and installing the new yields a yellow screen of darn noting missing files in the `...x64` directory.  Via the kudu console, I xcopied the files from the regular directory into a `...x64` directory I created and the cert updater sprung back to life.

**Comment by sjkp** [comment]
@robrich the none x64 bit site extension should not have anything in the x64 folder. 

if you use runfrompackage, then the site extension gets installed to
`D:\home\SiteExtensions\letsencrypt`
With the following folder structure
```
    App_Data
        jobs
            continuous
    bin
        de
        es
        fr
        it
        ja
        ko
        roslyn
        ru
        zh-Hans
        zh-Hant
    config
        httpsacme-staging.api.letsencrypt.org
    Content
    fonts
    Scripts
    Views
        Home
        Shared
```

And the web job should be located at 
`D:\home\site\jobs\continuous\letsencrypt(letsencrypt.siteextension.job)`


If you are not using `runfrompackage` then the web job will be deployed to `D:\home\site\wwwroot\App_Data\jobs\continuous\letsencrypt(letsencrypt.siteextension.job)`
