### ISSUE TITLE
Validation errors on ResourceGroupName and ServicePlanResourceGroupName

### ISSUE THREAD

**Issue by MorayM** [sjkp/letsencrypt-siteextension#254]
A simple bug, but in the setup guidance, ResourceGroupName is listed as optional, however leaving it blank gives a validation error indicating that ResourceGroupName is required.

**Comment by MorayM** [comment]
More experiments, entering my ResourceGroupName and leaving ServicePlanResourceGroupName gives the error message `The Service Plan Resource Group registered on the Web App in Azure in the ServerFarmId property 'Default' does not match the value you entered here` which has me pretty stumped!

**Comment by nguyenhuuloc304** [comment]
I have the same error. then I tried ResourceGroupName value for ServicePlanResourceGroupName (I mean I put into ResourceGroupName and ServicePlanResourceGroupName text boxes same value), then it worked
