### ISSUE TITLE
Renew Cert error Getway Timeout.

### ISSUE THREAD

**Issue by Keither** [sjkp/letsencrypt-siteextension#257]
When i renew Cert, client put getway timeout.

Response status code does not indicate success: 504 (Gateway Timeout)

var body = JsonConvert.SerializeObject(newCert, JsonHelper.DefaultSerializationSettings);
var t = client.PutAsync($"/subscriptions/{azureEnvironment.SubscriptionId}/resourceGroups/{azureEnvironment.ServicePlanResourceGroupName}/providers/Microsoft.Web/certificates/{newCert.Name}?api-version=2016-03-01", new StringContent(body, Encoding.UTF8, “application/json”)).Result;
t.EnsureSuccessStatusCode();

Sorry my English not good!
Thanks!

**Comment by sjkp** [comment]
If the Gateway timeout is momentarily then the extension will now retry.
