### ISSUE TITLE
Nothing happens when requesting cert

### ISSUE THREAD

**Issue by cadilhac** [sjkp/letsencrypt-siteextension#26]
I followed the step by step guide and everything seemed to go well, until the very last step.
When I click on "request and install certificate", the bowser spinner turns a few seconds, then stops and nothing changes on the page (well, in fact page reloads with same content). No mention of succes or failure. I try to go to my https://site but it says there is no cert.

**Comment by cadilhac** [comment]
My issue looks like #18
In fact my .well-known folder was not accessible from outside, so I fixed that. The "request and install certificate" button seems to do nothing again, but this time, I see that some content is created under the config folder. Unfortunately I see only the Signer and Registration folders and no certificate. In the other issue, the guy installed a newer version of the extension and it fixed it but I just installed the extension so I am up to date on this.

**Comment by cadilhac** [comment]
Follow-up:

I simply closed the browser window for the extension and started again. This time, I got an exception in your code. Sorry, I didn't copied the text. I can just remember the message "Could not find certificate" followed by a cryptic string.
So I checked the config folder again and this time I see many files (pem, der, pfx, ...) so I guess that the certificate has been generated by letsencrypt. But when I go back to https://.......scm.azurewebsites.net/letsencrypt/Home/Hostname I see a cert in the bottom certificates section and nothing in the bindings. In the portal, under the SSL bindings, I can't select any cert for the domain. So it seems the exception broke something...

**Comment by Anheledir** [comment]
Seems to be the same error as #23

**Comment by sjkp** [comment]
@cadilhac are you using a setup where app hosting plan and web app are in separate resource groups? if so check #23.

**Comment by cadilhac** [comment]
Thank you, that was it. I think the guide was not mentionning this one...
Your extension is a great initiative. Thank you for that. I hope you will be able to refine it to report all the errors that may happen during the process of generating a cert. Also it would be great if you could add the first steps like generating the AD app and the principal...

**Comment by sjkp** [comment]
@cadilhac thanks for the feedback. I have started writing my own docs, that should document this aspect better. And have some ideas for improving the UI to avoid this kind of errors in the future.
