### ISSUE TITLE
Sort HostNames?

### ISSUE THREAD

**Issue by brianrutter** [sjkp/letsencrypt-siteextension#263]
Would it be ok to sort the HostNames? I have 100+ domains and it is sometimes hard to find the correct domain based on the default order.

https://github.com/sjkp/letsencrypt-siteextension/blob/d597d53856fa5815e21ed013a4073925aa085ed6/LetsEncrypt-SiteExtension/Controllers/HomeController.cs#L193

**Comment by sjkp** [comment]
For sure, make PR. And I will merge it in with the next release.

**Comment by brianrutter** [comment]
Thanks Simon!

#265
