### ISSUE TITLE
Problems about multiple web jobs

### ISSUE THREAD

**Issue by crisspatri** [sjkp/letsencrypt-siteextension#266]
Do you know how to program a date for the web job? I mean i don't need it be "continuos", because this gives problems about my memory percentage.
I hope your answers, thanks

**Comment by sjkp** [comment]
So when do you want the job to run? Per default it runs 22 days before the expiration. If you want to force it to run e.g. on the first sunday of every month I suggest that you use the version without the web jobs, and trigger the renewal process using an azure function with a timer trigger that satisfy your preference. I have a blog post on how to do so here: 

https://wp.sjkp.dk/lets-encrypt-azure-functions-and-managed-service-identity/
