### ISSUE TITLE
Support for node.js

### ISSUE THREAD

**Issue by sjkp** [sjkp/letsencrypt-siteextension#27]
Need to check that the extension works with e.g. node express sites on azure. 

https://community.letsencrypt.org/t/letsencrypt-on-azure/11540

**Comment by RaananW** [comment]
Works. On express js add the following line in app.js (or anywhere else you wish):
```javascript
app.use('/.well-known', express.static('.well-known'));
```

**Comment by hoonio** [comment]
Not sure if this will help anyone else having same issues using node.js, but I had public folder tied to the site root, and wildcard matching to index.html which caused acme-challenge request to redirect to index.html. Adding the line below will stop redirect from happening, which prevented challenge file from being served. 

```
app.get('/.well-known/acme-challenge/:fileid', function(req, res){
  res.send('Requesting '+fileid)
})
```

For more details, [this is how my server.js looks like](https://github.com/hoonio/root/commit/6b5945a25a352709d334138aece149b425aebf83)
