### ISSUE TITLE
Is the WebJob used by this site extension affected by Azure Scheduler being retired?

### ISSUE THREAD

**Issue by gaelian** [sjkp/letsencrypt-siteextension#274]
Just wondering if anyone knows, does the retirement of Azure Scheduler on September 30, 2019 adversely affect App Service WebJobs and thusly the way that this site extension renews certificates? I got an email from Azure last September telling me I'm using Azure Scheduler and that I need to move to Azure Logic Apps before the shut-off date for Azure Scheduler. But as far as I am aware, the only scheduled task style thing I have running in Azure right now is the App Service WebJob used with this site extension.

**Comment by sjkp** [comment]
The extension doesn't use Azure Scheduler ( it was an old scheduling service that was available in the old portal, but it is not tied to azure web apps or azure web jobs, it could be used to call any http service on a predefined schedule). The extension uses azure web jobs, which is still going strong :)
