### ISSUE TITLE
Server Error in '/letsencrypt' Application

### ISSUE THREAD

**Issue by iTikoz** [sjkp/letsencrypt-siteextension#278]
I am trying to setup a subdomain and after deploying the .net function on Azure side I am facing a problem using the extension.

I am getting the following error message:

The Lets Encrypt ACME server was probably unable to reach http://subdomain.domain.com/.well-known/acme-challenge/SmSpIgBkmVPLo4zRFL4GbL3_dPgWySi7l-UGFNVHFsM view error report from Lets Encrypt at "xxxxxx" for more information

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: The Lets Encrypt ACME server was probably unable to reach http://subdomain.domain.com/.well-known/acme-challenge/SmSpIgBkmVPLo4zRFL4GbL3_dPgWySi7l-UGFNVHFsM view error report from Lets Encrypt at "xxxxxx" for more information

It seems as if the token cannot be accessed from the directory ".well-known/acme-challenge/" and thus the authentication fails

The error report on the "xxxxxx" link:

`{
  "identifier": {
    "type": "dns",
    "value": "domain.subdomain.com"
  },
  "status": "invalid",
  "expires": "2018-12-27T13:38:33Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/gxiSFvYtZp7R3__Q_2zXw6AY2t9kixipir11o34yVt8/211171943",
      "token": "_fCKSRu-Iq1I3B108HrHniFsE6fhLhaiucOrL0XliVA"
    },
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://subdomain.domain.com/.well-known/acme-challenge/SmSpIgBkmVPLo4zRFL4GbL3_dPgWySi7l-UGFNVHFsM [52.174.35.5]: 500",
        "status": 403
      },
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/gxiSFvYtZp7R3__Q_2zXw6AY2t9kixipir11o34yVt8/211171944",
      "token": "SmSpIgBkmVPLo4zRFL4GbL3_dPgWySi7l-UGFNVHFsM",
      "validationRecord": [
        {
          "url": "http://subdomain.domain.com/.well-known/acme-challenge/SmSpIgBkmVPLo4zRFL4GbL3_dPgWySi7l-UGFNVHFsM",
          "hostname": "subdomain.domain.com",
          "port": "80",
          "addressesResolved": [
            "52.174.35.5"
          ],
          "addressUsed": "52.174.35.5"
        }
      ]
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/gxiSFvYtZp7R3__Q_2zXw6AY2t9kixipir11o34yVt8/211171945",
      "token": "2JC-wKN68gK8SsRh_moxzqc3MRJut02Q8mHCOQVXLsk"
    }
  ],
  "combinations": [
    [
      2
    ],
    [
      1
    ],
    [
      0
    ]
  ]
}`

**Comment by sjkp** [comment]
Are you sure you have anonymous access enable to the well-known folder looks like let's encrypt get a 403.

**Comment by iTikoz** [comment]
@sjkp thanks a lot for your response, I have restarted the whole process and re-deployed the project on Azure after updating the SDK and now it works and the certificates are finally installed. Not sure what was the cause.

> Are you sure you have anonymous access enable to the well-known folder looks like let's encrypt get a 403. 

How to make sure of that, for future reference.

**Comment by sjkp** [comment]
@iTikoz  depends on what type of application you host in the web app. But if you want to test that it works, just place a simple html or txt file in D:\home\site\wwwroot\.well-known\acme-challenge you can use the kudu site to do so. Then test that you can browse that file, without logging in and without https. The site extension places a file in that folder that Let's encrypt validates the existence of in order for you to prove ownership of the domain.
