### ISSUE TITLE
Microsoft.Rest.Azure.CloudException  the client with object id does not have authorization

### ISSUE THREAD

**Issue by vhusker** [sjkp/letsencrypt-siteextension#279]
I had this extension working, and then moved my resource group containing my website to a new subscription.  I created a new service principal, granted it permissions, and went to update the settings.  I even uninstalled and reinstalled the extension.  

The error is:
`Microsoft.Rest.Azure.CloudException: The client '8a4189b6-ab3f-4238-be16-6274cacb56c8' with object id '8a4189b6-ab3f-4238-be16-6274cacb56c8' does not have authorization to perform action 'Microsoft.Web/sites/read' over scope '/subscriptions/aa958f19-5397-4638-9815-3eec0a9e9f6f/resourceGroups/jacobbensonio/providers/Microsoft.Web/sites/jacobbenson'. at Microsoft.Azure.Management.WebSites.WebAppsOperations.<GetWithHttpMessagesAsync>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.<GetAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.Get(IWebAppsOperations operations, String resourceGroupName, String name) at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model) in D:\a\1\s\LetsEncrypt-SiteExtension\Controllers\HomeController.cs:line 40`

What I don't understand is where that client and object ID is coming from.  My client id (application ID of the new app registration) is 3ea94083-9ef0-4989-8674-1d40e3f19638 .

What am I doing wrong?

**Comment by vhusker** [comment]
In case someone else sees this it, I was able to fix it by deleting the settings out of the Web App for Lets Encrypt.  It must have been pulling something (or something) from there and not allowing me to update it through the KUDU portal.

**Comment by sjkp** [comment]
In general moving web apps is still not as smooth as it should be. Glad you figured it out.
