### ISSUE TITLE
Your extension SCM page shows certs for all my apps

### ISSUE THREAD

**Issue by cadilhac** [sjkp/letsencrypt-siteextension#28]
Hi,
I started adding a cert for a second azure app. On the scm page of your extension for this second app, I am surprised to see the certs for the first app. Is it normal?

**Comment by cadilhac** [comment]
Even more strange: when I go in the azure portal, into the certificates section for my second app, I see the first app also listed!

**Comment by sjkp** [comment]
Certificates are installed on the App Service Plan level, so yes if you are using the same App Service Plan for multiple sites, this is expected behavior. 
The App Service Plan is in fact a virtual machine behind the scenes, so your certifcates are installed onto it.
