### ISSUE TITLE
Add Wiki Troubleshoot Section

### ISSUE THREAD

**Issue by LanceMcCarthy** [sjkp/letsencrypt-siteextension#282]
Add an additional bullet to the "No certificate gets installed" section of the Troubleshooting wiki article

### No certificates gets installed

* Check that you can successfully browse /.well-known/acme-challenge/ If you can't browse the challenge file, then Let's encrypt's servers can't issue a certificate for you. Not being able to browse it might be caused by using a hosting environment that doesn't support the file type used by the challenge file. The standard installation places a web.config in the folder, that allows the iis server to serve the file, but if you are e.g. using Java/PHP/ASP.Net core node.js you might have to do something within your own application to make the file browsable.

* The challenge file is browsable, but I still don't get any certificates Is DNS working for your site? The challenge file should be accessible via the DNS name you are requesting a SSL certificate for.

*  **If certificate is generated but fails to install with a "Cannot use SNI SSL with this plan" error, check that the Web App is scaled up to an App Service Plan that supports SNI SSL (at least B1)**

**Comment by sjkp** [comment]
Thanks added it :) 👍
