### ISSUE TITLE
WebJob exception

### ISSUE THREAD

**Issue by rafajraposo** [sjkp/letsencrypt-siteextension#283]
Hi,

I using the extension in some of my websites and in one of those the webjob was uninstalled after update to a new version so I had to reinstall the whole extension so it shows up again. That's when I started having the following problem:

> Unhandled Exception: System.InvalidOperationException: Microsoft.WindowsAzure.Storage is deployed incorrectly. Are you missing a Table Service assembly (Microsoft.Data.Services.Client, Microsoft.Data.OData or Microsoft.Data.Edm) or a related binding redirect? ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

After that the webjob just stay at "Pending restart" status forever, I checked the connection strings and they are added just right.

**Comment by theDiverDK** [comment]
Cool, was just going to report this issue.

I am having the exact same problem, unfortunately :(

**Comment by sjkp** [comment]
Ouch, I made a bo bo then. Forgot to update the app.config file for the web jobs. I will have to retract the release and make a new one. Sorry.

**Comment by sjkp** [comment]
I have unlisted 0.8.9 from nuget so you can reinstall the old version, or you can wait  a few hours until I get home so that i can prepare a fixed version.

**Comment by rafajraposo** [comment]
@sjkp I have reinstalled 0.8.8 and the webjob is running as expected. Thanks.

**Comment by theDiverDK** [comment]
I did the same, installed 0.8.8 and it works again :)

Thanks for the very cool extension, and very quick reaction to a problem :)

**Comment by sjkp** [comment]
Release 0.8.10 which should fix it.
