### ISSUE TITLE
Certificate {Guid} was not found

### ISSUE THREAD

**Issue by JamesReate** [sjkp/letsencrypt-siteextension#29]
![image](https://cloud.githubusercontent.com/assets/2886324/13381756/e55d5214-de31-11e5-9a1b-277766faf879.png)

Some things to know about my setup:
Updated to version 0.4.5
Using 64 bit
Using the same service principal and Storage account for other website secured with letsencrypt

Thanks

**Comment by cadilhac** [comment]
Just had this problem. Can Letsencrypt access your .well-known folder in your wwwroot directory?

**Comment by sjkp** [comment]
@JamesReate are app hosting plan and web app in same resource group if not take a look at #23

**Comment by cadilhac** [comment]
Sorry, I mixed 2 different issues here. Forget what I said about the well-known folder.

**Comment by cadilhac** [comment]
@JamesReate it's time you add error reports to your app ;) people (me included) keep posting duplicate issues here...

**Comment by sjkp** [comment]
@cadilhac well I would love to detect the above error if I could - but I can only assume that, it's the error - no way to know for a fact. :/

**Comment by JamesReate** [comment]
Yup, same as #23 , closing this issue. Should have looked in the "closed" issues first.
