### ISSUE TITLE
Error when install 

### ISSUE THREAD

**Issue by carloscds** [sjkp/letsencrypt-siteextension#290]
System.NullReferenceException: Object reference not set to an instance of an object. at LetsEncrypt.SiteExtension.Controllers.HomeController.<Index>d__1.MoveNext() in D:\a\1\s\LetsEncrypt-SiteExtension\Controllers\HomeController.cs:line 0

**Comment by sjkp** [comment]
Can you provide more information? I can't reproduce the error - at which point in the install process did you get this? And which environment did you try to install it in.

**Comment by carloscds** [comment]
Hi, after change ResourceGroup to name instead letsencrypt-siteextension. It's work!

**Comment by sjkp** [comment]
Ah, I see now. Yes that is a bad error message for providing a none existing resource group, will provide a better message.

**Comment by carloscds** [comment]
@sjkp As suggestion, put more clear messages :-) But congratulations for this extension!
