### ISSUE TITLE
Azure WebApp Slots bug

### ISSUE THREAD

**Issue by micyb1** [sjkp/letsencrypt-siteextension#291]
Hi.
I have tried to install certificate on slot in webapp (in main app, everything is works fine).
I am in extension and when I choose custom domain and put my e-mail address and click Request and Install Certificate after few second I have an error:

I am on site: https://webapp-portal-web-01.scm.azurewebsites.net/letsencrypt/Home/Install

Server Error in '/letsencrypt' Application.
________________________________________
The remote name could not be resolved: 'webapp-portal-web-01-webapp-portal-web-02.scm.azurewebsites.net' 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.WebException: The remote name could not be resolved: 'webapp-portal-web-01-webapp-portal-web-02.scm.azurewebsites.net'

Source Error: 

An unhandled exception was generated   during the execution of the current web request. Information regarding the   origin and location of the exception can be identified using the exception   stack trace below.

My main site name is: webapp-portal-web-01, slot name is webapp-portal-web-02
DNS for main is: webapp-portal-web-01.azurewebsites.net and for slot is webapp-portal-web-01-webapp-por.azurewebsites.net

I don't know why extension wants something from dns address that is combination of main and slot app name.

**Comment by micyb1** [comment]
Ok, I know where is the problem.
Extension always use dns name in format: mainappname-slotappname.azurewebsites.net
But if your main app name and slot name is too long, azure cut dns name. 
Extension should get DNS name of slot app from configuration.

**Comment by sjkp** [comment]
This is fixed in 0.9.3. @micyb1 thanks for the accurate error report 👍
