### ISSUE TITLE
Wiki update suggestion

### ISSUE THREAD

**Issue by kyleballard** [sjkp/letsencrypt-siteextension#293]
In the "How to Install" wiki, one item I struggled with figuring out for a while, was that the "Application Id/Client Id" should not be the "Name" value from the Key that is created.  It should be the actual Application Id of the registered app that is created inside Azure AD.

Would propose updating the line:
"Application ID/CLIENT ID - as your user name."
To:
"Application ID/CLIENT ID - as your user name.  (note:  This is the Id of the Azure Application you created, not the name of the key)."

Or something to that effect.  Will hopefully save someone else some trouble.   Thank you so much for creating this awesome extension btw.   Really can't say how appreciated it is to be able to get a free SSL certificate on Azure with it.

**Comment by sjkp** [comment]
Thanks for the input, I have updated the wiki to reflect your suggestion.
