### ISSUE TITLE
Unable to install certificate

### ISSUE THREAD

**Issue by karshikarr** [sjkp/letsencrypt-siteextension#301]
- I am trying to install a certificate, however getting the below error:
 The Lets Encrypt ACME server was probably unable to reach http://mywebapp/.well- 
  known/acme-challenge/pbDbb0sOljLGfkqL4U35Y8cDT8pI0sh8fZXK7RLyOHE view error report 
 from Lets Encrypt at https://acme- 
 v01.api.letsencrypt.org/acme/authz/SFa_Me7ya7XAfBMloURFBHE_pQHl for more information

- I checked the logs on https://acme- 
 v01.api.letsencrypt.org/acme/authz/xxx and it gives error 403

- Both the app service plan and Web app are in the same resource group.

- The service principal has contrib access to the resource group.

- Attaching the logs

[Letsencryptlogs.docx](https://github.com/sjkp/letsencrypt-siteextension/files/2983184/Letsencryptlogs.docx)

**Comment by sjkp** [comment]
Do you have authentication enabled on your web site? Because if you get a 403 it seems like Lets encrypt are unable to browse the challenge file. 

It is hard for me to provide you better guidance when you don't want to share your site, if you want you can share it in an email to me.

**Comment by karshikarr** [comment]
Hi Simon,

Thank you for responding, currently there are IP restrictions set up on the WebApp which allow only internal users to access the WebApp.

If someone tries to access it via external network they get an error 403 site is stopped.

I will try to remove the IP restrictions and test.

Thanks again,

Rohan Karshikar
WillisRe Technology - Senior Associate

Willis Towers Watson

Rohan.Karshikar@willistowerswatson.com<mailto:Rohan.Karshikar@willistowerswatson.com>
willistowerswatson.com<https://www.willistowerswatson.com/>

Follow Willis Towers Watson on social media<https://www.willistowerswatson.com/en/social-media>
