### ISSUE TITLE
Compilation issue on Install.cshtml

### ISSUE THREAD

**Issue by paulallington** [sjkp/letsencrypt-siteextension#303]
Installing a new certificate and getting the following compilation error at /letsencrypt/Home/Install

There is no ViewData item of type 'IEnumerable<SelectListItem>' that has the key 'Hostnames'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: There is no ViewData item of type 'IEnumerable<SelectListItem>' that has the key 'Hostnames'.

Source Error: 
Line 22:             @Html.LabelFor(model => model.Hostnames, htmlAttributes: new { @class = "control-label col-md-2" })
Line 23:             <div class="col-md-10">
Line 24:                 @Html.ListBoxFor(model => model.Hostnames, ViewBag.HostNames as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
Line 25:                 @Html.ValidationMessageFor(model => model.Hostnames, "", new { @class = "text-danger" })
Line 26:             </div>

Source File: D:\home\SiteExtensions\letsencrypt\Views\Home\Install.cshtml    Line: 24

**Comment by sjkp** [comment]
Hi @paulallington 
This is a bug - but if you assign a custom hostname to your web site (which you need to do anyway, to get any Let Encrypt certificate issued) then you shouldn't see this error.

**Comment by paulallington** [comment]
How do you do that in azure?  It has a number of custom host names associated with it
