### ISSUE TITLE
Crash when trying to request and install certificate

### ISSUE THREAD

**Issue by fkorsa** [sjkp/letsencrypt-siteextension#305]
The let's encrypt Azure extension crashed when I clicked on "request and install certificates". Here is the log:

Server Error in '/letsencrypt' Application.
There is no ViewData item of type 'IEnumerable<SelectListItem>' that has the key 'Hostnames'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: There is no ViewData item of type 'IEnumerable<SelectListItem>' that has the key 'Hostnames'.

Source Error: 

Line 22:             @Html.LabelFor(model => model.Hostnames, htmlAttributes: new { @class = "control-label col-md-2" })
Line 23:             <div class="col-md-10">
Line 24:                 @Html.ListBoxFor(model => model.Hostnames, ViewBag.HostNames as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
Line 25:                 @Html.ValidationMessageFor(model => model.Hostnames, "", new { @class = "text-danger" })
Line 26:             </div>

Source File: D:\home\SiteExtensions\letsencrypt\Views\Home\Install.cshtml    Line: 24 

Stack Trace: 

[InvalidOperationException: There is no ViewData item of type 'IEnumerable<SelectListItem>' that has the key 'Hostnames'.]
   System.Web.Mvc.Html.SelectExtensions.GetSelectData(HtmlHelper htmlHelper, String name) +228
   System.Web.Mvc.Html.SelectExtensions.SelectInternal(HtmlHelper htmlHelper, ModelMetadata metadata, String optionLabel, String name, IEnumerable`1 selectList, Boolean allowMultiple, IDictionary`2 htmlAttributes) +118
   System.Web.Mvc.Html.SelectExtensions.ListBoxFor(HtmlHelper`1 htmlHelper, Expression`1 expression, IEnumerable`1 selectList, IDictionary`2 htmlAttributes) +93
   System.Web.Mvc.Html.SelectExtensions.ListBoxFor(HtmlHelper`1 htmlHelper, Expression`1 expression, IEnumerable`1 selectList, Object htmlAttributes) +69
   ASP._Page_Views_Home_Install_cshtml.Execute() in D:\home\SiteExtensions\letsencrypt\Views\Home\Install.cshtml:24
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +105
   System.Web.WebPages.StartPage.RunPage() +17
   System.Web.WebPages.StartPage.ExecutePageHierarchy() +73
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +78
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +256
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +291
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() +198
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
   System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +577
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0

**Comment by andr3w** [comment]
I'm getting the same issue.

**Comment by sjkp** [comment]
@andr3w can you try release 0.9.6 and let me know if that fixes it. I cant reproduce the error, so if 0.9.6 doesnt help you have to provide more info. 
What is your web app setup like (which region, are you using app service plan and web app in same resource group)

**Comment by andr3w** [comment]
Thanks. I'll try that and come back to you with more details.

**Comment by fkorsa** [comment]
Personally it was a one-time issue, unfortunately. I simply refreshed and clicked again and it worked. I just wanted to report it in case the call stack would help you.

For me, region is West Europe, and app service plan and web app are in the same resource group indeed.

**Comment by andr3w** [comment]
Hi Simon,

Thanks for taking the trouble to reply.
I've been unable to recreate that error.
I've now got everything in the same resource group and everything seems to
be working.
A possible causes... the storage account was in a different resource group
and possibly in a different region; absolutely no good reason for this
other than me selected the default "create a new resource group"
unthinkingly.
At one stage I think I had some things in the same resource group but in
different regions.

Anyway thanks very much for the extension. I find tasks such as renewing
certificates extraordinarily dangerous. I figure how to complete them,
then, one or two years later; when it has to be redone I can be almost
certain that the portal will have changed and my notes, if I can find them,
will be useless.

Andrew
