### ISSUE TITLE
Not Continuing after "Request and Install"

### ISSUE THREAD

**Issue by RaananW** [sjkp/letsencrypt-siteextension#31]
Hi,

I have everything configured (hopefully correctly), and am now trying to receive a certificate. 
in the install window (/letsencrypt/Home/Install) i choose the domain, enter a mail and click the request button.
The site loads, but never forwarded to the domain window. When clicking the back button, all of the domains' SSL state is disabled.

However, in the WebJobs, I see 2 success jobs - 

* Functions.SetupHostNameAndCertificate
* Functions.RenewCertificate

Both jobs have no output, but the state is marked "success".

Any tips on what I could be checking to get it to work?

**Comment by sjkp** [comment]
Please see https://github.com/sjkp/letsencrypt-siteextension/wiki/Troubleshoot 
Also you can look at the closed issues for more troubleshooting tips. 

let me know how it goes.

**Comment by RaananW** [comment]
That did the trick. 
The well-known directory was not accessible.
Thanks a lot!
