### ISSUE TITLE
Blank page when cert request fails

### ISSUE THREAD

**Issue by chadwackerman** [sjkp/letsencrypt-siteextension#32]
I added a new sub domain to my site and received a blank page after requesting the certificate. I couldn't recall if this was normal or an error. The issue turned out to be an inaccessible challenge directory, but the path to a solution was not clear.

Troubleshooting docs state:

> Check that you can successfully browse /.well-known/acme-challenge/

I tripped over the obvious here as well. This directory is not browsable (nor should it be, of course). Suggest something like:

> Verify that you can successfully browse /.well-known/acme-challenge/[name of challenge file] over http (not https). A list of challenge files is available via the SCM:
> 
> https://[your-site].scm.azurewebsites.net/api/vfs/LocalSiteRoot/VirtualDirectory0/site/wwwroot/.well-known/acme-challenge/
> 
> (You may need to change "VirtualDirectory0" as well depending on your hosting configuration.)

Thanks again for your work on this. Hopefully my fumbling can save others some time.

**Comment by sjkp** [comment]
Thanks for your feedback. It seems that I need to handle the scenario where the challenge file isn't browsable better - a lot of people are getting that error, because it largely depend on what you are hosting on azure whether or not it is browsable.

**Comment by sjkp** [comment]
Closing this with the better error reporting introduced in 0.4.9.
