### ISSUE TITLE
Cannot Request certificate: Account creation on ACMEv1 is disabled.

### ISSUE THREAD

**Issue by kjartab** [sjkp/letsencrypt-siteextension#328]
Struggling with a azure web app with extension 0.9.6. Upon retrieving a staging certificate through the extension window, it crashes with the following stack trace.

Have tried replacing the v01 endpoint with v02 in app settings, but it results in the same error.

From what I understand the extenion supports ACME v2, not sure what is going wrong here though. Also, the readme still refers to the v1 endpoint even though v2 seems to be the new standard and v1 is to be deprecated.

[WebException: The remote server returned an error: (403) Forbidden.]    System.Net.HttpWebRequest.GetResponse() +1339    ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) in D:\a\1\s\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:708  [AcmeWebException: Unexpected error  +Response from server: 	+ Code: Forbidden 	+ Content: {   "type": "urn:acme:error:unauthorized",   "detail": "Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.",   "status": 403 }]    ACMESharp.AcmeClient.Register(String[] contacts) in D:\a\1\s\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:171    LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer) in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:146    LetsEncrypt.Azure.Core.Services.<RequestCertificate>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:41    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58    LetsEncrypt.Azure.Core.<RequestInternalAsync>d__16.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:231    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58    LetsEncrypt.Azure.Core.<RequestAndInstallInternalAsync>d__17.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:244    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58    LetsEncrypt.SiteExtension.Controllers.<Install>d__7.MoveNext() in D:\a\1\s\LetsEncrypt-SiteExtension\Controllers\HomeController.cs:250    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58    System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97    System.Web.Mvc.Async.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult) +17    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32    System.Web.Mvc.Async.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0() +58    System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228    System.Web.Mvc.Async.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult) +10    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34    System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() +35    System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +100    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27    System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45    System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26    System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10    System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +575    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163
--

**Comment by sjkp** [comment]
Version 1.0.1 now uses the ACMEv2 API please update to that.
