### ISSUE TITLE
Renew already fresh certificates?

### ISSUE THREAD

**Issue by Zebusch** [sjkp/letsencrypt-siteextension#33]
Hi! Im not sure if i am making a mistake or not but my certs get renewed every time the jobs are executed. I see in the logs that it says "No certificates installed issued by Let's Encrypt that are about to expire within the next 14 days. Skipping."

But then i also found in the code: `if (settings.Hostnames.Any())` on line 63 in CertificateManager.cs. Why is the method RequestAndInstallInternal ran if there are any hostnames? I mean, the foreach loop above should already take care of this, right? At least i think this might be the reason i get new certs all the time...

**Comment by sjkp** [comment]
Well there could be an issue, I have to do some digging. But SetupHostnameAndCertificate is only supposed to be called from the webjob once, after the first install. I can see however that I set https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt. SiteExtension.WebJob/Functions.cs#L39 RunOnStartup = true, which is a problem if you restart your site, then I suppose that it will run it again.

**Comment by sjkp** [comment]
Added extra logic to the job to prevent it from running more than once.
