### ISSUE TITLE
No account exists with the provided key

### ISSUE THREAD

**Issue by mikmeh** [sjkp/letsencrypt-siteextension#334]
Getting this on 4 different sites currently. 

Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-acct'.
urn:ietf:params:acme:error:accountDoesNotExist: No account exists with the provided key

**Comment by sjkp** [comment]
If you don't mind please add what fixed it for you - then it can be a help to other people experiencing the same issue.

**Comment by mikmeh** [comment]
TBH, it just started working. I was able to manually renew certs through let's encrypt so I don't think they were down. I was actually trying to figure out a way to delete this.
