### ISSUE TITLE
(403) Forbidden - Acme v1 issue

### ISSUE THREAD

**Issue by narcis-mihai** [sjkp/letsencrypt-siteextension#343]
HI, I'm trying to renew the certificate but I get this error:
I read the documentation and it might be because the tool is using ACME v1 and let's encrypt removed the support for it...

[WebException: The remote server returned an error: (403) Forbidden.]
   System.Net.HttpWebRequest.GetResponse() +1341
   ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) in D:\a\1\s\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:708

[AcmeWebException: Unexpected error
 +Response from server:
	+ Code: Forbidden
	+ Content: {
  "type": "urn:acme:error:unauthorized",
  "detail": "Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.",
  "status": 403
}]
   ACMESharp.AcmeClient.Register(String[] contacts) in D:\a\1\s\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:171
   LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer) in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:146
   LetsEncrypt.Azure.Core.Services.<RequestCertificate>d__5.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\Services\AcmeService.cs:41
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   LetsEncrypt.Azure.Core.<RequestInternalAsync>d__16.MoveNext() in D:\a\1\s\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:231

**Comment by ohadschn** [comment]
You need to use the latest version of the extension (ACME V2 is used since 1.0.1):
https://github.com/sjkp/letsencrypt-siteextension/releases
