### ISSUE TITLE
The '.well-known/acme-challenge' directory is not created

### ISSUE THREAD

**Issue by TallGuy789** [sjkp/letsencrypt-siteextension#346]
I'm having a problem with the Let's Encrypt challenge. The extension does not seem to be able to create the '.well-known/acme-challenge' directory (and hence the key file thing inside it). There is no error that is specific to creating the directory & file - the challenge just fails:

> `Unable to complete challenge with Lets Encrypt servers error was: {"type":"http-01","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/1855503472/LC1kUw","status":"Invalid","validated":null,"error":{"Type":"urn:ietf:params:acme:error:unauthorized","Detail":"Invalid response from https://www.<mysite>.co.nz/.well-known/acme-challenge/<challenge key> [13.77.7.175]: 404","Identifier":null,"Subproblems":null,"Status":403},"errors":null,"token":"<challenge key>","keyAuthorization":null}`

The URL referenced does not exist because the extension did not create the '.well-known/acme-challenge' directory and key file in it.

I installed the 'Azure Let's Encrypt (No Web Jobs)' extension months ago and that worked fine (including creating the '.well-known/acme-challenge' directory. Yesterday I uninstalled it, deleted the '.well-known/acme-challenge' directory (for a 'clean' install), and installed the web jobs version as I wanted to try and get the automatic renewal working. The extension has not been able recreate the directory since.

I've uninstalled and re-installed both versions of the extension several times and got the same results. Each time I went through the set up & ticked the 'Update Application Settings and Virtual Directory (if needed)' check box. I have restarted the site multiple times. I also have a different App Service in the same Azure subscription that works fine.

It's a little odd that the extension was not able to create the directory, but didn't seem to get any error at that point. Any ideas what could be causing this?

**Comment by TallGuy789** [comment]
I've managed to fix this problem. I'm still not exactly sure what the problem was or exactly what fixed it, but I will list everything I did. Hopefully, it might help someone else.

- Using the Azure Portal, copied all the letsencrypt:* application config settings & values and then deleted them all.
- Using the Kudu portal, removed the existing Azure Let's Encrypt extension.
- Using an FTP Client, deleted the following directories:
  - `/data/letsencrypt`
  - `/site/siteextensions/letsencrypt.webapponly`
  - `/site/wwwroot/.well-known`
  - `/SiteExtensions/letsencrypt`
  - `/SiteExtensions/letsencrypt.webapponly`
- Using the Azure Portal, in the LetsEncrypt application registration, deleted the existing client secret and created a new one.
- Using the Kudu portal, re-install the Azure Let's Encrypt extension.
- Restart the site.
- Run the extension, go through the setup and let it re-create the application config settings with the values I saved earlier and the new client id.

**Comment by sjkp** [comment]
If you have installed the version of the site-extension called letsencrypt webapponly then it is not surpising that autorenewal doesn't work, because that version doesnt include the webjob that does auto-renewal. That version was intended for people who wanted to control the renewal themselves using the API included in the site extension, e.g. from logic apps some other external triggering service. Now since you say you had two folders, it is hard to know if what was really setup, so a complete uninstall as you described, was a good idea.
