### ISSUE TITLE
Feature request: add connection string UI fields to configuration

### ISSUE THREAD

**Issue by benjaminhowarth1** [sjkp/letsencrypt-siteextension#347]
For some reason, when I deploy my site to my Azure web app, the connection strings in my web.config are not picked up. I finally figured out how to add the connection strings manually to the app using the portal UI, however, there's an API that also allows this. I've got a PR ready to submit.

**Comment by madsoulswe** [comment]
@sjkp this breaks install on "No Web Jobs"-version. DashboardConnectionString and StorageConnectionString are set to required.

![image](https://user-images.githubusercontent.com/7071187/72259378-98411480-3610-11ea-9df5-ea042350388e.png)

**Comment by sjkp** [comment]
@benjaminhowarth1 Yes im aware, but you can fill in anything you want when using the no-webjob version.

**Comment by Marcel0024** [comment]
The connection strings are the same as the settings in Configuration right? So i can just copy/paste them? It keeps hanging on this screen:

![image](https://user-images.githubusercontent.com/14852157/72328029-75ffd300-36b2-11ea-8aef-c1ec51c0d37d.png)

And then i get:

![image](https://user-images.githubusercontent.com/14852157/72327946-510b6000-36b2-11ea-872a-61c03ce432d9.png)

The documentation should also be updated with this breaking change

**Comment by vinsuz** [comment]
@Marcel0024 I tried pasting the settings in and it hung for me as well until I added AzureWebJobsStorage and AzureWebJobsDashboard as Connection Strings rather than App Settings to the app's configuration.

Sorry if this was already covered by someone.
