### ISSUE TITLE
MVC/ WebApi application can not expose .well-known directory for listing

### ISSUE THREAD

**Issue by wonderxboy** [sjkp/letsencrypt-siteextension#35]
I tried to add the following block in web.config to enable directory listing for /.well-known path

```
<location path=".well-known">
    <system.webServer>
      <directoryBrowse enabled="true" />
    </system.webServer>
  </location>
```

But I get the following error.

Configuration Error

> Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 
> 
> **Parser Error Message: <location> path attribute must be a relative virtual path.  It cannot start with any of ' ' '.' '/' or '\'.**
> Source Error: 
> 
> 
> Line 15:     <section name="authenticationProviders" type="SimpleAuthentication.Core.Config.ProviderConfiguration, SimpleAuthentication.Core" />
> Line 16:   </configSections>
> Line 17:   <location path=".well-known">
> Line 18:     <system.webServer>
> Line 19:       <directoryBrowse enabled="true" />

**Comment by chadwackerman** [comment]
You don't need to do this. Nor do you want directory browsing enabled. The site extension adds a rule to access the individual files within.

See #32 for some documentation improvements I suggested plus a way to find a filename under .well_known so you can verify that the files themselves are accessible from outside.

**Comment by sjkp** [comment]
The site extension writes a web.config file to the /.well-known/acme-challenge/ folder with the following content. So you shouldn't need to do what you are trying. 
```
<?xml version = "1.0" encoding="UTF-8"?>
 <configuration>
     <system.webServer>
         <staticContent>
             <mimeMap fileExtension = "." mimeType="text/json" />
         </staticContent>
     </system.webServer>
 </configuration>
```
