### ISSUE TITLE
1.0.5  DashboardConnectionString and StorageConnectionString not documented

### ISSUE THREAD

**Issue by ramon-mendes** [sjkp/letsencrypt-siteextension#354]
I really don't know where to look for this two fields:

![image](https://user-images.githubusercontent.com/44581176/73295114-db40e180-41e5-11ea-92da-68035548399f.png)

The 'How-to-install' doesn't mention them... https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install

**Comment by Feldegast123** [comment]
Solved by adding two custom connection strings named AzureWebJobsDashboard and AzureWebJobsStorage. Set the connection string to the storage account you want to use under storage account ->access key (and pick either of them).

**Comment by ramon-mendes** [comment]
AzureWebJobsStorage is OK, But what about AzureWebJobsDashboard, where do I find it?

**Comment by Feldegast123** [comment]
Ah, just put the same connection string in both. (I'm not sure if that is correct but it's working) :)

**Comment by ramon-mendes** [comment]
It doesn't for me:
![image](https://user-images.githubusercontent.com/44581176/73846275-08ebe300-4803-11ea-890e-90ea25938080.png)

**Comment by BastienPerdriau** [comment]
Hi,

We tried to put the same connection string in both as well and we have the same error than @ramon-mendes here.

**Comment by Feldegast123** [comment]
Like this:

![image](https://user-images.githubusercontent.com/13996442/73925445-5ed98d00-48ce-11ea-9229-83173c803432.png)

**Comment by BastienPerdriau** [comment]
@Feldegast123 In my web app, they are stored in the app settings, not in the connection strings.

I let it run half a day, the page told me it was refreshing.
I clicked on the button to refresh manually and I got the same error message than ramon-mendes above.
I re-tried today and same result.

**Comment by Feldegast123** [comment]
I added as connection string first but they exist in appsettings too.

**Comment by Solnake** [comment]
I've done all the same as @Feldegast123 suggested and it works for me. Just add AzureWebJobsDashboard and AzureWebJobsStorage connection strings which point to the same storage and it will works. I've tried in the beginning add prefix "letsencrypt:" and add it as app settings values and it didn't work.

**Comment by BastienPerdriau** [comment]
Hi, I misreaded your first comment.

So yes, I added manually into Connection Strings settings and it's now ok !

Thank you !

**Comment by CyberSauce** [comment]
I can't get this to work. I've tried the connection strings, but just keep getting an error.

**Comment by Dudleydogg** [comment]
I don't get error but the Extensions asks to configure Host Names which I did a few years ago and worked with previous version.

**Comment by CyberSauce** [comment]
> I don't get error but the Extensions asks to configure Host Names which I did a few years ago and worked with previous version.
> Mine is working now Just had to clean up the config strings remove "Slots" and it ran fine.

I got mine. I had to create a gen1 storage account on the same resource group and copy the string for both AzureWebJobsDashboard and AzureWebJobsStorage. The string can be the same for both entries in the webapp.

**Comment by sjkp** [comment]
I have updated the docs to reflect the new fields added in 1.0.5.

**Comment by CyberSauce** [comment]
Thanks @sjkp

**Comment by ItsBradMorgan** [comment]
> It doesn't works for me:
> ![image](https://user-images.githubusercontent.com/44581176/73846275-08ebe300-4803-11ea-890e-90ea25938080.png)

@ramon-mendes  Did you ever get this solved?

**Comment by Dudleydogg** [comment]
Yes you need to just add those two variables with a connect string to a storage account.
![image](https://user-images.githubusercontent.com/12835026/75887407-c0224c80-5df7-11ea-9e76-b94736ce7fbd.png)

**Comment by ItsBradMorgan** [comment]
> Yes you need to just add those two variables with a connect string to a storage account.
> ![image](https://user-images.githubusercontent.com/12835026/75887407-c0224c80-5df7-11ea-9e76-b94736ce7fbd.png)

Unfortunately, I have tried that recreated the storage account and variables multiple times. After clicking Next it just spins forever and then I get the same error about AzureWebJobsStrorage and AzureWebJobsDashboard that OP posted.

**Comment by Dudleydogg** [comment]
Ok I would remove the Extension all together.  Reboot the web app, Then add it again, I also had to do this when the version changed recently. Mine would not detect custom Domains even though there were custom domains.  After removing everything, then console into web app and clear out the folders for letsencrypt.   reboot web app. and add extension again.  That would be my suggestion.

**Comment by ItsBradMorgan** [comment]
Thanks @Dudleydogg . Unfortunately, the problem persist even with uninstalling > restart > install > restart...very frustrating.
![image](https://user-images.githubusercontent.com/5844317/75891941-81dc5b80-5dfe-11ea-8c67-cc6ff17f5f96.png)

![image](https://user-images.githubusercontent.com/5844317/75892071-ba7c3500-5dfe-11ea-95ad-9f00ba9d9070.png)

![image](https://user-images.githubusercontent.com/5844317/75892327-2068bc80-5dff-11ea-9ab6-ea7c2e70f3ed.png)

**Comment by Feldegast123** [comment]
Did you add them as custom connectionstrings (not appsettings) under webapp configuration?

**Comment by ItsBradMorgan** [comment]
Thank you @Feldegast123! I cannot believe I missed that, it worked right away after that...

**Comment by Feldegast123** [comment]
Your welcome! 😊

**Comment by Dudleydogg** [comment]
Yes forgot about that they moved from Appsetting to Connection String good Catch.
Feldegast
