### ISSUE TITLE
Possible race condition in Authorize

### ISSUE THREAD

**Issue by chadwackerman** [sjkp/letsencrypt-siteextension#36]
Changed the Sleep below from 4000 to 10000 and I'm getting staging certs reliably now. Solves #30 for me as well. I'm still having issues with production certs. After web.config is rewritten I'm getting error 304 on the challenge files for a few seconds while the server reconfigures.

```
// TODO: put timeout/retry limit in this loop
while (authzState.Status == "pending")
{
    Console.WriteLine(" Refreshing authorization");
    Trace.TraceInformation("Refreshing authorization");
    Thread.Sleep(10000); // this has to be here to give ACME server a chance to think
    ...
```

**Comment by chadwackerman** [comment]
After adding the following code to CertificateManager.cs I am able to reliably get non-staging certs. Providing code here as a bug report instead of via pull request as this whole site extension needs to be rethought. It's way too far gone for an outsider to deal with. Frankly you should provide a warning that it's not ready for production use in the current state.

```
var answerUri = new Uri(httpChallenge.FileUrl);
Console.WriteLine($" Answer should now be browsable at {answerUri}");
Trace.TraceInformation("Answer should now be browsable at {0}", answerUri);

var retry = 10;
while (true)
{
    using (var client = new HttpClient())
    {
        Thread.Sleep(1000);
        var x = client.GetAsync(answerUri).Result;
        Trace.TraceInformation("Checking status {0}", x.StatusCode);
        if (x.StatusCode == HttpStatusCode.OK) break;
        if (retry-- == 0) break;
        Trace.TraceInformation("Retrying {0}", retry);
    }
}
```

**Comment by sjkp** [comment]
@chadwackerman thanks for your feedback. 

Nowhere do I state that this is ready for production, in fact the version of the site extension should clearly indicate that it is beta software 0.4.5, just as well as lets encrypt is in public beta. 

Of course I can never provide a perfect integration with Azure web sites (the site extension model is not ideal for that), so we have to wait for Microsoft. This site-extension is here to fill a gap, until Microsoft adds similar functionality, if they want to. My guess is that they are gonna do something similar to Lets Encrypt themselves making all this irrelevant.

**Comment by chadwackerman** [comment]
I landed on this extension after it was endorsed by Nir Mashkowski at Microsoft who claimed it was reviewed by Microsoft folks. I now think he might have been overly-excited. I certainly don't mean to be overly-critical of your work but I agree that the site extension model is not going to work for this any time soon. I also agree that Microsoft is likely to provide free SSL certs like Amazon does long before they fix the site extension programming model, kicking this stuff out of the picture altogether.

That said you probably have at least a few thousand sites using this thing now and they're all gonna go dark over the next few months as web jobs fail on timeouts. I don't know if it's possible to force updates but it's a bad situation. I think it deserves a prominent warning at the top of the github page. Luckily I'm not in production because this basically took me down for a week until I had time to learn Microsoft's latest wacky extension model for websites. Lesson? It's just as screwed up as the stuff they were pushing with IIS 3 and 4 and 5 and 6 and 7...
