### ISSUE TITLE
ACMEv1 is being deprecated by letsencrypt - from June 1st no renewals will work

### ISSUE THREAD

**Issue by ocoster** [sjkp/letsencrypt-siteextension#368]
I have gotten an email from letsecrypt:

> According to our records, the software client you're using to get Let's
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
in the past two weeks using the ACMEv1 protocol. Here are the details of one
recent ACMEv1 request from each of your account(s):
>
> Client IP address:  xxx.xxx.xxx.xxx
>
> User agent:  ACMEdotNET v1.0.0.0 (ACME 1.0)
>
> Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail. For most people, simply upgrading to
the latest version of your existing client will suffice. You can view the
client list at: https://letsencrypt.org/docs/client-options/
>
> ACMEv1 API deprecation details can be found in our community forum:
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1

This means that in a couple of weeks no renewals done with this site extension will work.

**Comment by ocoster** [comment]
I appears that the latest [Certes](https://github.com/fszlin/certes) version does support ACMEv2, so, one assumes a library upgrade will suffice (though I have no clue if the API changed)?

**Comment by ohadschn** [comment]
The extension was updated to V2 a long time ago: https://github.com/sjkp/letsencrypt-siteextension/releases/tag/1.0.1

My WebJob, based on this extension, has been working off it since with no issue: https://github.com/ohadschn/letsencrypt-webapp-renewer

**Comment by ocoster** [comment]
I've updated the extension on kudu to the latest version (1.0.5), got a new cert and still got that email, so not sure where the disconnect it.

**Comment by ohadschn** [comment]
No configuration necessary, you can check the WebJob logs to verify the V2 endpoint was used.
Perhaps you got this mail for an old renewal?

**Comment by ohadschn** [comment]
Also maybe verify that you don't have 2 WebJobs installed somehow (I'm not sure if that can happen with the extension, as mentioned above I'm using my own WebJob based on this code).

**Comment by ocoster** [comment]
OK, not sure what's going on - possible I renewed with the old version of the extension. Will wait and see if the next renewal works.
