### ISSUE TITLE
Can this be used with multiple app services sharing one storage account? 

### ISSUE THREAD

**Issue by carbontwelve** [sjkp/letsencrypt-siteextension#37]
The question is pretty much in the title, but I am wondering if there would be any conflicts if I used one storage account for all app services using this site extension? 

Or is it required that each site has its own storage account for this extension?

**Comment by sjkp** [comment]
You have to create separate storage accounts. The lock file is not unique per app service. Also it is free to create the storage account, so don't see why you would not just make separate accounts.

**Comment by carbontwelve** [comment]
@sjkp thanks for the reply and clarification. Having separate storage account's isn't a huge problem, its mostly that we have hundreds of app services, and therefore will need to set up hundreds of storage accounts. It just becomes a little cumbersome with the azure portal being what it is ;)

**Comment by sjkp** [comment]
@carbontwelve you should look into ARM template or ARM in general. With that many app services I really wouldn't want to manage them manually. You take a look at the template I use here https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt.ResourceGroup/Templates/azuredeploy.json

**Comment by carbontwelve** [comment]
@sjkp ARM templates are a good idea for going forward; I had looked into them previously but they looked rather complex given at the time I didn't know too much about how Azure actually works.
