### ISSUE TITLE
Web job not renewing certificates

### ISSUE THREAD

**Issue by thusithagh** [sjkp/letsencrypt-siteextension#381]
We have 3 deployment slots in an Azure app plan, which has 3 different domain names like below:

Production - --
Stage - --
Stable - --

We have Azure Let's Encrypt extension and a web job running which should renew the certificates after 1.5 months.
We noticed that the renewal hasn't been run as it should have been, so we ran it manually for production and stage manually yesterday, and it was a success. 
We left stable as is to see if we can find out the problem.

We'd really appreciate if you someone could point out the way to troubleshoot and find out the cause why this hasn't worked.
Thank you.

**Comment by joelnotified** [comment]
Hi @thusithagh 
Currently experiencing the same problem. Cert renewal has stopped working for us. Have you found a solution?

**Comment by thusithagh** [comment]
Not really, and this project is not seems to be active anymore as well. @joelnotified

**Comment by joelnotified** [comment]
@thusithagh Looks like it could be related to this in my case, so I'm hoping there will be a merge and release of that pretty soon: https://github.com/sjkp/letsencrypt-siteextension/pull/382

**Comment by sjkp** [comment]
Please try again with release 1.0.6

**Comment by alexmaie** [comment]
Thanks for the update 👍

**Comment by joelnotified** [comment]
Thanks a lot @sjkp. 1.0.6 is working for us! ⭐
