### ISSUE TITLE
Could not load File or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by jamesbascle** [sjkp/letsencrypt-siteextension#39]
My website blob logs are getting spammed with this every 60 ~~minutes~~ seconds on the dot.

2016-03-23T16:01:43,Error, \<websiteName\>,07bfaa,635943457034371652,0,9192,6,"Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.",

I checked via FTP, and /SiteExtensions/letsencrypt64/bin contains Newtonsoft.Json.dll

**Comment by sjkp** [comment]
Hi @jamesbascle thanks for your report, which version of the site-extension are you running? I'm not able to reproduce the error when I run in 64bit mode myself. If you are not on the latest version could you please do an upgrade. 

The web jobs doesnt run in the directory you looked in. Upon installation of the site extension the web job is installed in the wwwroot, under \App_Data\jobs\continuous\letsencrypt.siteextension.job so can you please check here. Also worth checking in that folder is the  LetsEncrypt.SiteExtension.WebJob.exe.config it should look like this
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <!-- The format of the connection string is "DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY" -->
    <!-- For local execution, the value can be set either in this config file or through environment variables -->
    <add name="AzureWebJobsDashboard" connectionString="" />
    <add name="AzureWebJobsStorage" connectionString="" />
  </connectionStrings>
    <startup> 
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by jamesbascle** [comment]
I'm running the 64bit version, using the latest 0.4.7.  It looks as if Newtonsoft.Json.dll is, in fact, present at that location as well.  The config file you mentioned is also correct.

**Comment by jamesbascle** [comment]
Sorry I forgot to update...seems fine now.  Was getting a small bug of saying it couldn't find the WEBSITE_OWNER_NAME variable as well, but that seems to be fixed now too. :+1:
