### ISSUE TITLE
It does nothing...

### ISSUE THREAD

**Issue by djanosik** [sjkp/letsencrypt-siteextension#4]
This looks like a good idea, but when I click on "Request and Install certificate" it does nothing. It should at least display what is wrong.

**Comment by hazzik** [comment]
It works for mw, could you explain what do you mean by "does nothing"?

**Comment by djanosik** [comment]
Well, I don't know what does it mean. The page will reload and nothing happens... i guess it's because the `RequestAndInstallInternal` function returns `null`.

**Comment by hazzik** [comment]
I suspect that you have exceeded weekly limit on the certificates request,
but not sure.

Let's sjkp investigate.

**Comment by djanosik** [comment]
I don't think so. I use staging.

**Comment by sjkp** [comment]
@djanosik could you try while having the log stream open to see what is writes to the stream (I have not central loggin in place, so can't see what failed on your instance).

**Comment by djanosik** [comment]
Ok, it was because challenge files were not accessible (returning 404). The challenge files are of unknown type and are not served by ASP.NET 5 by default. Thank you for your help!

**Comment by Yitzchok** [comment]
djanosik How did you fix this?

**Comment by Yitzchok** [comment]
This worked for me

   app.UseStaticFiles(new StaticFileOptions()
            {
                ServeUnknownFileTypes = true,
                DefaultContentType = "text/json"
            });

**Comment by sjkp** [comment]
Yes I write a web.config file to the folder, to allow serving of the files. But if you are hosting with something that don't understand web.config files, then you need to do something yourself.
