### ISSUE TITLE
"Browse" button no longer there under Extensions in Azure?

### ISSUE THREAD

**Issue by CyberBill** [sjkp/letsencrypt-siteextension#414]
I've used Lets Encrypt for a long while, and typically what happens is that after installing the site extension, when I click on the "Extensions" tab under my App Service it will show a 'Browse' button on the screen so that I can configure it.

However I recently made some changes to add another App Service and another instance of Let's Encrypt, and updated a bunch of things on my sites, and that 'Browse' button is no longer there. I just see a list of extensions, which lists Let's Encrypt, but there is no way for me to access it to configure or refresh my certificate.

I *believe* I should be able to access Let's Encrypt by accessing https://blah.azurewebsites.net/letsencrypt/# or perhaps just /letsencrypt/ - but none of these seem to work. I'm curious if anyone would have any suggestions for debugging this?

My thinking is that an update to my site (I updated all NuGet packages, for example) changed some security setting that doesn't allow the Azure Let's Encrypt Extension to be accessible, but don't know what to look for there.

Thanks for any assistance!

**Comment by kenyvice** [comment]
After a big research i found the "link", based on your example domain, you found it there: 
https://blah.scm.azurewebsites.net/letsencrypt
put **.scm.** between blah and azurewebsite and **/letsencrypt** to the end

**Comment by BillCarlson** [comment]
BRILLIANT!!!  Yes, this is exactly what I was looking for, and works perfectly.

Thank you a million times over. :)

**Comment by skir** [comment]
There is the other way to access Let's Encrypt: 
1. Go to your app service's Advanced Tools to open Kudu portal.
2. Select "Site Extensions" in the top menu bar.
3. Press "Launch" button for Let's Encrypt extension.

**Comment by CyberBill** [comment]
That is great! I can confirm that this method also works!

**Comment by CyberBill** [comment]
I'm going to mark this as 'closed', as I realize now that I've got two workarounds, that's good enough. :)

**Comment by skir** [comment]
More good news on this topic: Azure team brought back the "Browse" button.
<img width="1110" alt="Screenshot 2023-10-04 at 17 36 58" src="https://github.com/sjkp/letsencrypt-siteextension/assets/5897847/df609fe2-21a8-4af8-89ce-19622152b0cd">
