### ISSUE TITLE
Server Error in '/letsencrypt' Application. The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by allensanborn** [sjkp/letsencrypt-siteextension#45]
Everything was going fine when I was going through the "Azure Let's Encrypt" setup until I hit "Request and Install Certificate" and I hit "Request and Install certificate". The page was working away and then threw the exception below. The .well-known folder was created. It is the 32bit version on a 32 bit site and is all contained in a single resource group. 

Any ideas?

Server Error in '/letsencrypt' Application.

The request was aborted: Could not create SSL/TLS secure channel.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[WebException: The request was aborted: Could not create SSL/TLS secure channel.]
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +606
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +64

[HttpRequestException: An error occurred while sending the request.]

[AggregateException: One or more errors occurred.]
   System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) +3632429
   System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +11532455
   System.Threading.Tasks.Task`1.get_Result() +33
   LetsEncrypt.SiteExtension.Core.CertificateManager.Authorize(Target target) in c:\Projects\LetsEncrypt-SiteExtension\LetsEncrypt-SiteExtension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:550
   LetsEncrypt.SiteExtension.Core.CertificateManager.Auto(Target binding) in c:\Projects\LetsEncrypt-SiteExtension\LetsEncrypt-SiteExtension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:441
   LetsEncrypt.SiteExtension.Core.CertificateManager.RequestAndInstallInternal(Target target) in c:\Projects\LetsEncrypt-SiteExtension\LetsEncrypt-SiteExtension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:244
   LetsEncrypt.SiteExtension.Controllers.HomeController.Install(RequestAndInstallModel model) +605
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +169
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9644037
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by allensanborn** [comment]
This is possibly due to me having set the App Service Plan to Basic and then forgetting that it needs to be in at least the Standard tier to allow for custom domains AND certs as opposed to the just the custom domains that the Basic tier allows. I'll test again when I get a chance and hopefully not run into an error. If that is the case I'll try to check to see if I can add a more appropriate error message.

**Comment by sjkp** [comment]
The latest version of the code tries to get the challenge file from your server after it is generated, before asking for a certificate from letsencrypt. It seems like it is failing on that precheck. It is failing due to an SSL error - which is kinda odd, since it should not be trying on https unless you have something that redirects from http to https, do you have that?

**Comment by allensanborn** [comment]
Why yes I do! I'm driving everything through Cloudflare and I've set it to Full which allows me to not have to create my own cert for the domain. I'll try turning that off and going through the setup again this weekend and let you know how it goes.
Thanks!

**Comment by sjkp** [comment]
@allensanborn did it resolve your problem?

**Comment by allensanborn** [comment]
Yes it did. I'm sorry I didn't follow up.

**Comment by macbroadcast** [comment]
Hi @allensanborn i have the same problem (lets encrypt cert ) going thru cloudflare with settings "full" how did you fixed the issue ?

**Comment by allensanborn** [comment]
It was my impression that Let's Encrypt really doesn't like going through https to hit the .well-known folder at the root of the website. This was a requirement that I didn't realize until @sjkp pointed that out. 

I ended up not using Cloudfront so I don't know if there is an easy way to exclude that folder from using https. From the web site's point of view though you can make sure that you don't have a redirect to https from http for that folder. That can be done in your web.config using the Application Request Routing redirect rules. You should be able to find stuff on that on StackOverflow pretty easily.

**Comment by macbroadcast** [comment]
ok sorry thought you were talking about cloudflare not cloudfront ,never mind i will figure it out , maybe i will just create a cert on cloudflare instead of using my LE cert and put it on myserver :smiley_cat:

**Comment by allensanborn** [comment]
Sorry. That was just a typo. I was using Cloudflare. I corrected that in the original statement.
As far as I know there shouldn't be an issue with you setting Cloudflare to Full Strict SSL. 
The only issue is getting the Let's Encrypt cert in the first place. I did that with this Azure Web Sites plugin and I just turned off my https redirects for the .well-known folder and dumped Cloudflare since I didn't really need it for my client. I was mostly concerned about just getting them using https. 
I believe if you have Cloudflare's SSL turned on at all it will redirect all http traffic to https which would make it impossible to set up Let's Encrypt.


https://www.cloudflare.com/ssl/
Full SSL (strict):
Encrypts the connection between your site visitors and CloudFlare, and from CloudFlare to your server.

You will need to have a valid SSL certificate installed on your server, and the certificate must be signed by a trusted certificate authority and have not expired.
Visitors will see the SSL lock icon in their browser.

**Comment by darrenshrwd** [comment]
My certificate is not renewing and I have enabled HTSTS without knowing about this requirement to use http for that folder, so it seems because I enabled HSTS I cannot allow http to any folder and my site is basically f**ked when my certificate expires, I am correct or is there a way out of this situation?

Can I fully just pass through cloudflare and then it will work perhaps?

**Comment by sjkp** [comment]
According to the following Lets encrypt doesn't care about hsts:
https://community.letsencrypt.org/t/what-happens-with-a-challenge-if-hsts-is-enabled-but-wrong-no-certificate-provided/14938 

The site extension checks if the acme-challenge folder is accessible https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt.SiteExtension.Core/CertificateManager.cs#L551, I didn't test that with HSTS enable, so that might be causing issues.

**Comment by darrenshrwd** [comment]
Ok, thanks for the reply, it is still working on my test site which is on a subdomain so actually perhaps this is not it, actually today it is giving a totally different error so I'll put that into a new issue.

**Comment by darrenshrwd** [comment]
...Which I then closed (https://github.com/sjkp/letsencrypt-siteextension/issues/75) ...I was able to get it to renew by turning off cloudflare on naked and www in the end, guess I tried to quickly other time, will see what happens in a couple of months.
