### ISSUE TITLE
Is it possible to delete certificates?

### ISSUE THREAD

**Issue by zappod** [sjkp/letsencrypt-siteextension#46]
Hi.

I've had to delete and create a web app to move it from one app service plan to another (different regions). But now I can't install a new certificate on the new web app -> Exception: The resource 'xxx.yyy.zzz' already exists in location 'southcentralus' in resource group 'Default-WebApp-WestEurope'. A resource with the same name cannot be created in location 'West Europe'. Please select a new resource name. 

Is there any way to delete existing certificates?

**Comment by sjkp** [comment]
You can do it from the portal? But if you already removed the old resource group with its appservice plan it seems a bit strange that it is not deleted. If the resource group still just open another website in the app service plan and delete it from there.
![image](https://cloud.githubusercontent.com/assets/3397744/15174135/56bd7c06-1760-11e6-837b-fb832ef875fb.png)

**Comment by zappod** [comment]
The certificates does not show up in the "custom domain and ssl" view. It might be because the original app service plan is deleted, but I can't find the problematic certs any other place than when I try to add new ones to the new site. When I try to add new one I get the error:
_The resource 'mywebsite.com' already exists in location 'southcentralus' in resource group 'Default-WebApp-WestEurope'. A resource with the same name cannot be created in location 'West Europe'. Please select a new resource name_
I've also tried to look through the cert store progamatically, but no luck..

**Comment by zappod** [comment]
By looking at your code I managet to figure out how the extension extracts the certs. Then I wrote a little program to loop through and delete the certs giving me issues. So it's all good again.

Thanks for a great extension!

**Comment by sjkp** [comment]
Sound like encountered a bug with the ARM API, I can't believe that it should leave certs behind, but great to hear that you found a fix and that my code was of help to you.
