### ISSUE TITLE
Certificates for multiple domains

### ISSUE THREAD

**Issue by djanosik** [sjkp/letsencrypt-siteextension#5]
Please, make it possible to request certificates for multiple domains (eg. www and non-www).

**Comment by hazzik** [comment]
It is possible. What is your issue?

**Comment by djanosik** [comment]
I cannot select multiple domains when requesting a certificate. I have to generate multiple certificates (one for each domain).

**Comment by sjkp** [comment]
Are you using manually or auto? You have to setup the domain bindings first.

**Comment by djanosik** [comment]
I have bindings for `xyz.com` and `www.xyz.com`. I had to generate two certificates (one for each domain). But it's wrong, it should be possible to generate one certificate for both domains. 

I am using "manually". I had to click through the 3 step dialog.

**Comment by sjkp** [comment]
I wasn't awere that letsencrypt allowed you to add serveral subdomains to the same certificate. So that is something I have to fix.

**Comment by SpikeTheMaster** [comment]
This would be a useful feature to have :+1:

**Comment by sjkp** [comment]
It is supported by https://github.com/Lone-Coder/letsencrypt-win-simple now - so I will look at their code and get it to work with the extension as well.
