### ISSUE TITLE
Failed on Step3 of Grant permissions to the Service Principal

### ISSUE THREAD

**Issue by kooboo-binbin** [sjkp/letsencrypt-siteextension#50]
We don't have Active directory already.
So I create a new active directory named webshoq. after that I create a new application named letsencrypt
On step3 I enter the name letsencrypt. I get an error message "There is no user in Standaardmap with the full name matching 'letsencrypt' "

The active directory "webshoq" in in the Standaardmap.

**Comment by sjkp** [comment]
It looks like there is already another active directory, linked to your subscription named Standaardmap that. If I try to got to https://manage.windowsazure.com/Standaardmap.onmicrosoft.com i get redireted to a login page as if it exists. Maybe you are not global admin and is unable to see it?
