### ISSUE TITLE
Support for Mobile Apps?

### ISSUE THREAD

**Issue by tomh4** [sjkp/letsencrypt-siteextension#51]
Hey,
is that supported? Can I add an SSL Cert this way to a Mobile App in Azure ? I cannot find the Extensions tab...

**Comment by sjkp** [comment]
I would think so - but I have tried. Will update, when I have tested it out.

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by tomh4** [comment]
Thanks, please get back to me, I got stuck at the step where I should install the extension, the azure mobile app has no extension button...

**Comment by sjkp** [comment]
My newly created mobile app, have just the same options as a web site (as it should, since they are basically the same). 
![image](https://cloud.githubusercontent.com/assets/3397744/16242600/7d2ea474-37f3-11e6-9673-c10b0254326b.png)
If you dont have the extension tab, I guess you can always navigate to <yourdomain>.scm.azurewebsites.net and install the extension from there.

**Comment by tomh4** [comment]
Hm weird I cannot see it! Ill try trough the link then, thanks a lot for your support and the great tool!
