### ISSUE TITLE
Trying to Generate a SSL certificate for a deployment slot with a custom domain

### ISSUE THREAD

**Issue by rbonini** [sjkp/letsencrypt-siteextension#52]
If you have a deployment slot with a custom domain (beta.yoursitename.com), setting up lets encrypt defaults to the parent application name and domains. You can not choose to generate a certificate for beta.yoursitename.com. Only for yoursitename.com.

We need to be able to change this behavior

(I know azure gives out one for yoursitenamebeta.azurewebsites.net, but a custom domain is much more convenient)

**Comment by sjkp** [comment]
Thanks for the feedback. I have as noted on the front page not tested the extension with deployment slots. I might do a update for you, and the few other people who have asked for it, since I have started to use deployment slots myself for canary testing  :)

**Comment by twilly86** [comment]
Any update on this?  I'm in need of this to get application initialization to warm up my site.  Right now I get an ssl error on my deployment slot and no warm up happens since my deployment slot doesn't have a valid ssl cert.  I can assist with development if you point me in the right direction.

**Comment by adityanag** [comment]
I'd like this enhancement as well. I tried setting it up using a different storage account, but no luck. 

I'm happy to help you test this out if you need some beta testers.

The extension works great on my primary site, btw, it's really excellent

**Comment by aaronwJordan** [comment]
@sjkp I'd like to add another +1 here.

A wonderful extension you've built here and I think there are a lot more than just a few people who would like to see deployment slot support.

Thanks again for this extension.
