### ISSUE TITLE
Example site https://schdo.com/ certificate has expired

### ISSUE THREAD

**Issue by infogulch** [sjkp/letsencrypt-siteextension#54]
![invalidcert](https://cloud.githubusercontent.com/assets/133882/16502126/6bf68bd2-3ed2-11e6-88f6-d8005f51b212.png)

It expired 	Wed, 29 Jun 2016 15:57:00 UTC, 1 day 3 hours ago.

**Comment by sjkp** [comment]
Thanks for the heads up. I was playing around with my site, when doing the investigation with Microsoft, so I messed the web job up, and now it have got myself throttled :/
