### ISSUE TITLE
Upcoming Azure AD signing cert roll-over

### ISSUE THREAD

**Issue by yoadsn** [sjkp/letsencrypt-siteextension#57]
Hey,
I believe letsencrypt site extension would not be affected by the upcoming certificate [roll-over of Azure AD on Aug-15th](https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/?WT.mc_id=azurebg_email_Trans_1150_Azure_AD_Certificate_Rollover_EN%20ONLY).
But since I did get an email from MS to check my AD apps, and letsencrypt was listed there - Wanted to make sure no one here thinks it might be affected.

The reason I think it will not be affected is because client applications need to present their token to the API service but not validate it. Only if your application validates signed JWT tokens you need to use the correct public key matching the private one used to sign the token.

Would welcome any input.

**Comment by sjkp** [comment]
Shouldn't affect the site extension. It is just using the client crendential flow, to get an access token it can use to talk to the ARM API.
