### ISSUE TITLE
Update documentation to generate Service Principal via powershell

### ISSUE THREAD

**Issue by twilly86** [sjkp/letsencrypt-siteextension#59]
Find the powershell script on this page to generate a Service Principal.  Should be much easier than doing this through the portal.

https://blogs.msdn.microsoft.com/visualstudioalm/2015/10/04/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-buildrelease-management/

**Comment by sjkp** [comment]
Thanks for the suggestion, the Site Extension it self actually have a link to that exact article, will added it to the documentation here too.
