### ISSUE TITLE
Extract subscription id and resource name from WEBSITE_OWNER_NAME variable

### ISSUE THREAD

**Issue by hazzik** [sjkp/letsencrypt-siteextension#6]
The `WEBSITE_OWNER_NAME` variable has format of `subscriptionId+ResourceName-webspace`

**Comment by sjkp** [comment]
That is useful, thanks!

**Comment by hazzik** [comment]
But I think this should be just a default. And let user change these, as
this feature is not documented anywhere

**Comment by sjkp** [comment]
Yes - but it will be a few things less to fill out. I'm working on automating the setup process even more. Expect an updated version during the weekend.

**Comment by hazzik** [comment]
Nice
