### ISSUE TITLE
The Lets Encrypt ACME server was probably unable to reach ...

### ISSUE THREAD

**Issue by kairovs** [sjkp/letsencrypt-siteextension#60]
Hi,
during the step of requesting certificate I receive error:
"Server Error in '/letsencrypt' Application.
The Lets Encrypt ACME server was probably unable to reach ..."
The path in the error message is like this: http://mydomain/.well-known/acme-challenge/...
If I copy it and paste in the browser I'm able to reach it, but it changes http to https like this
https://mydomain/.well-known/acme-challenge/...
I guess that's why LetsEncrypt reports error, but how to avoid it? Azure by default enable HTTPS for the web apps and it's not possible to switch it off. Any ideas?
Regards,
Roman

**Comment by kairovs** [comment]
Update - I got the answer although I don't like it :( The problem is not with site extension, but in fact that we allow incoming traffic to our web app only from specific ip addresses because our environment is just for internal testing currently.
LE don't have specific IP addresses used for validation so only option is to open access for everyone.
If anybody have any ideas/experience how to handle such situation then please let me know. Thanks!

**Comment by sjkp** [comment]
@kairovs - thanks for updating your issue with the explanation, this thread on LE's forum explains it a bit further: https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/13

However there is another option for validation the ownership of a domain than using the HTTP challenge, you can also do a DNS challenge (which the site extension doesn't support currently), but maybe that would be more useful in a scenario like yours.
