### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by sebastienros** [sjkp/letsencrypt-siteextension#62]
I have successfully setup the certificate, but did hit some issues on my way, which could be solved by updating the "How to install" wiki page:
1- When setting the "App Properties" for Azure Directory, the urls must be in the form of `schema://domain/path`, I was missing the `path` part and I got an error when running the extension later on.
2- When generating the certificate, there will be a request on the `.well-known` folder that is create by the extension, in my app static files access was not configured. There should be a warning explain that the app needs to be configured to serve static files from this folder.

I am not sure I can do a PR for wikis, if not and you want me to create the markdown for you I can do it.

**Comment by sjkp** [comment]
@sebastienros thanks for feedback I will, clarify the docs on those two steps.
