### ISSUE TITLE
Generating a certification fails if Authorisation is enabled

### ISSUE THREAD

**Issue by leewalkergm** [sjkp/letsencrypt-siteextension#67]
I've tested this with Azure Active Directory (AAD) enabled and it rightly fails.

Suggestions:
- Add a failure page to say "Sorry, auth was enabled, try turning it off whilst generating a certificate" (Bare minimum)
- Add a check to see if any auth is enabled on the site and tell the user before attempting to generate
- Add a step to check if auth is enabled, save the settings then disable auth until the certificate has been added/generated (Pie in the sky!)

**Comment by sjkp** [comment]
I can for a fact say that I'm not going to do bullet point 3, as I don't want to be responsible for something like that. If Auth is turned on it is probably for a reason, and I don't think a site extension should disable it, even if it is just for the challenge directory. The two other suggestions are very valid.

**Comment by leewalkergm** [comment]
Completely agree, I think even just the first which routes you back to the first page would be sufficient

**Comment by sjkp** [comment]
#101
