### ISSUE TITLE
Error when installing extension from scm on 64 bit environment

### ISSUE THREAD

**Issue by gldfdp** [sjkp/letsencrypt-siteextension#7]
I have the following error "Could not load file or assembly 'ManagedOpenSsl' or one of its dependencies" after having installed the extension through scm, restarted the site and try to launch the extension.

Thanks

**Comment by hazzik** [comment]
Need to turn of x64 applications

**Comment by gldfdp** [comment]
Thank you it corrects the bug. Is it planned to support 64 bits ?

**Comment by sjkp** [comment]
If I can find an easy fix. I will but - you unless you have a very specific reason to run 64 bit, you probably want to run 32bit anyways, less memory required, and if you are building for cloud you should build for scale out and not scale up (which 64 bit basically is). Check hanslemans blog on the topic http://www.hanselman.com/blog/PennyPinchingInTheCloudYourWebAppDoesntNeed64bit.aspx

**Comment by mbasil77** [comment]
What is the issue preventing 64-bit support?  What has to run native?

An extension shouldn't force you down a bit-path.  Especially one that which may lose support.

mb

**Comment by sjkp** [comment]
The extension uses ManagedOpenSsl32 and ManagedOpenSsl64 nuget packages (well not the extension,but ACMESharp with the extension relies on does). I have to figure out how to install the site extension with the correct assemblies depending on whether the website is running in 64 bit mode or not. Or get rid of the dependency to OpenSSL.

**Comment by mbasil77** [comment]
Interesting ... so it's really a packaging issue.  How did you get the project white-listed as an Azure Web Sites Extension?

mb

**Comment by mbasil77** [comment]
i see how to do that ... FYI ... I sent this ticket into Microsoft Support to see if they have any Advisory suggestions.

**Comment by mbasil77** [comment]
http://stackoverflow.com/questions/18446374/how-to-deal-with-x86-vs-x64-packages

**Comment by sjkp** [comment]
Well I can easily make a seperate version for 64 bit, but it would mean two different site extensions, which I don't think is very user friendly (but maybe better than not supporting 64bit?). My problem with the approach is that people probably don't remember to reinstall the site extension when they decide to go from 32bit to 64bit, eventually they will come here complaining that their SSL certs weren't renewed :/ 

It is easy to publish site extensions (there are not validation process) you just upload them to siteextensions.net

**Comment by mbasil77** [comment]
I agree with your comments about forgetting to change back and forth.  That
could lead to an invalid certificate.

I'll try to ask around about the conditional compilation.  I think that is
the best path forward.

mb

-- 
*Michael Basil*
312-436-1083
linkedin <http://www.linkedin.com/in/mikebasil>

**Comment by mbasil77** [comment]
Would some kind of assembly redirect work?

**Comment by mbasil77** [comment]
@sjkp I see some comments referencing this being worked on ... if you need people to test let me know

**Comment by sjkp** [comment]
It is up now, just pick the site extension with x64 in it's name. 

![image](https://cloud.githubusercontent.com/assets/3397744/12933194/2c1c8350-cf87-11e5-931a-745106d97f1f.png)

**Comment by mbasil77** [comment]
It works!  Great work.  I liked your approach.

-- 
*Michael Basil*
312-436-1083
linkedin <http://www.linkedin.com/in/mikebasil>
