### ISSUE TITLE
Umbraco requires special handling

### ISSUE THREAD

**Issue by akuryan** [sjkp/letsencrypt-siteextension#70]
Hi,
Since Umbraco intercepts all requests and tries to map them to items in database - this extension will fail.
Basing on suggestion at https://www.jdibble.co.uk/blog/using-letsencrypt-with-umbraco I've built small Nuget package, which allows to fix this problem: https://www.nuget.org/packages/LetsEncrypt.Umbraco/
Maybe it is wise to include it in https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install ?
Under the hood, this Nuget inherits from owin startup umbraco module and checks, if request is coming for anything in directory '.well-known'. If it is - and there is a file with such a name - module will serve it as a static file.

I've have had some discussion with one of maintainers of Umbraco and he agreed that this module can be useful ( https://github.com/akuryan/LetsEncrypt.Umbraco/issues/1 )

**Comment by sjkp** [comment]
Thanks a lot @akuryan - this is very useful, I will update the How to install.

**Comment by sjkp** [comment]
In fact I decided to make a separate page for this kind of information.
https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install-(on-various-platforms)

**Comment by akuryan** [comment]
Thank you
