### ISSUE TITLE
Allow IP Based SSL

### ISSUE THREAD

**Issue by jaykay-design** [sjkp/letsencrypt-siteextension#76]
As far as I can tell the certs installed use SNI automatically. Some sites require IP based SSL

**Comment by sjkp** [comment]
To my knowlegde that is not possible with letsencrypt (https://community.letsencrypt.org/t/certificate-for-static-ip/84), if you can help me find some documentation that it can be done please provide it here.

**Comment by hazzik** [comment]
@sjkp the link is different to what @jaykay-design is asking for. He asks for the option in the azure to install cert as the IP based SSL. Let's encrypt cert are working with this option perfectly. It can be changed here: 

![2](https://cloud.githubusercontent.com/assets/144791/19421300/0b5cd6b8-945a-11e6-8206-10cc08800543.PNG)

Microsoft Azure > App Services > [service name] - SSL certificates > Add SSL Binding

So, the issue shall be reopenned.

**Comment by hazzik** [comment]
It's about changing these 2 lines: https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt.SiteExtension.Core/CertificateManager.cs#L485 and https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt.SiteExtension.Core/CertificateManager.cs#L492 
to `IpBaseEnabled` based on settings.

**Comment by sjkp** [comment]
I see, I misunderstod the question. Out of curriosity what types of sites need to have the SSL cert bound to IP?

**Comment by jaykay-design** [comment]
WebApps which have to service older OS, browsers or libraries which can not do SNI yet. I have two of these and it's a roadblock for using LetsEncrypt.
Thanks for merging!
