### ISSUE TITLE
Configuration blocked 

### ISSUE THREAD

**Issue by gldfdp** [sjkp/letsencrypt-siteextension#8]
When I setup the extension and I click  on "Request and Install Certificate", nothing happens (the post redirect to the same page and no SSL is installed).

**Comment by Lanayx** [comment]
You can take a look at streaming logs (/api/logstream on your scm site) to see the error stacktrace.

**Comment by sjkp** [comment]
In the latest version if the installation fails, the exception will be clearly visible in the portal, should ease debugging.
