### ISSUE TITLE
Webjob exception

### ISSUE THREAD

**Issue by cadilhac** [sjkp/letsencrypt-siteextension#81]
Hi,

I have 2 websites using your extension. The first one had its cert correctly renewed by the web job. The second one did not renew so I checked the logs and it says this:

> The configuration is not properly set for the Microsoft Azure WebJobs Dashboard. 
> In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored. 

Under the portal, indeed, there is AzureWebJobsDashboard in the settings of the first app but not in the second app. I don't know why it happened... Should I just copy the value for the first app and add it in the settings of the second app? (also the AzureWebJobsStorage key is missing).

The installation of all this was made a long time ago a short time after you released your extension, so I don't remember how the webjob was setup and why there is a mismatch beetween 2 sites...

Thanks

**Comment by sjkp** [comment]
The extension doesn't add the connection strings automatically. So you have to set them up manually (my guess is that you maybe did that for one of the sites). Also currently I recommend against using the same storage account for two sites, I have not tested that scenario, and there might be some bugs if the two jobs are on the same storage account (like they at locking each other out, web jobs uses a azure storage for locking to avoid multiple runs on of the same job).

**Comment by cadilhac** [comment]
Thanks for the info SImon.
