### ISSUE TITLE
The Lets Encrypt ACME server was probably unable to reach .well-known/acme-challenge

### ISSUE THREAD

**Issue by ron159** [sjkp/letsencrypt-siteextension#82]
hi guys,
first of all,so sorry to ask this question again,but i did have read all questions which is same  to me before,and i try to fix it ,but it did't make any sense.
i used azure to create a wordpress web app ,and use this extension to get Let's Encrypt's ssl,after all things be done ,i get the problem. 
p.s. using 0.5
Thanks.

**Comment by ron159** [comment]
The problem has been solved.
The method:you have give the Azure Service permission to your MySQL  DataBase and the web app both.

**Comment by sjkp** [comment]
@ron159 that sounds great. 

I take it that means the site-extension works without problems with wordpress on azure web apps?

**Comment by ron159** [comment]
@sjkp  yeah ,thanks,your extension works good.
 but any one who wants to use the azure web app should pay attention to the permission setting.
