### ISSUE TITLE
The Lets Encrypt ACME server was probably unable to reach http://mydomain.com/.well-known/acme-challenge/

### ISSUE THREAD

**Issue by cltsang** [sjkp/letsencrypt-siteextension#84]
First of all thanks for the great extension.
This has probably been asked a lot, but I am not sure what I have done incorrectly in the final step.
My site is just the default empty web app, with php disabled, and applicationHost.xdt plus web.config file, to work as a reverse proxy server. It's not in a production slot, but I believe that doesn't matter right?
Do I need to give full rwx permissions to others in wwwroot folder?
I've checked Letsencrypt service principal is a contributor of the web app.
Thanks.

**Comment by sjkp** [comment]
Your reverse proxy settings are not forwarding traffic from the .well-known/acme-challenge folder is it?

**Comment by cltsang** [comment]
Thanks you are right. It's just I didn't add a rule to allow access to the folder. Thank you.
