### ISSUE TITLE
Unable to complete challenge with Lets Encrypt servers error was: pending

### ISSUE THREAD

**Issue by counterfitninja** [sjkp/letsencrypt-siteextension#86]
After pressing the Request and Install Certificate button to request the SSL i get the the following error message 

Unable to complete challenge with Lets Encrypt servers error was: pending

![capture20161114112224315](https://cloud.githubusercontent.com/assets/4258903/20263012/aef99942-aa5c-11e6-941b-607009dcd387.png)

**Comment by sjkp** [comment]
@counterfitninja where you able to get this to work at another time?
