### ISSUE TITLE
400 Bad Request when selecting domains with special characters

### ISSUE THREAD

**Issue by DDoerner** [sjkp/letsencrypt-siteextension#87]
When selecting a domain that contains a special character (in my case the german umlaut 'ü'), the site extension throws a 400 Bad Request (in the standard IIS error page)

**Comment by sjkp** [comment]
Thanks for the report, I will look into it over the weekend.

**Comment by goranhell** [comment]
Is this fixed? I have a swedish letter in a domain; ä.

**Comment by sjkp** [comment]
Should be fixed as part of 0.8.7

**Comment by goranhell** [comment]
Hi, 
I upgraded to 0.8.7, but I don't get it to work.
