### ISSUE TITLE
Document RenewXNumberOfDaysBeforeExpiration and set its default to anything larger than 20

### ISSUE THREAD

**Issue by ohadschn** [sjkp/letsencrypt-siteextension#91]
Hi,

A quick look through the code suggests that the `RenewXNumberOfDaysBeforeExpiration` `app.config` key can be set in order to  configure the number of days before a cert's expiry auto-renewal takes place.

This sounds like a pretty important setting, so it should probably be documented (ideally in the main page). In addition, seeing as the first expiration e-mail sent by let's encrypt is fired [20 days before expiry](https://letsencrypt.org/docs/expiration-emails/), I think it makes sense to try and renew it before, effectively making the let's encrypt mail an error indicator if anything went wrong. So a default of something like 22 would make more sense than 14 IMHO.

**Comment by sjkp** [comment]
Hi  @ohadschn good points. I will update the documentation and bump up the default value in the next release.

**Comment by ohadschn** [comment]
Thanks!

To clarify, I think 22 is better than 21 since the latter might be cutting it a bit close, depending on time zones (e.g. if one is Australia and the other US then the time difference between them could almost reach a full day).

**Comment by ohadschn** [comment]
@sjkp I just ran into some LE documentation that suggests renewing every 60 days (meaning the default value should be 30 if you wish to follow their recommendation): https://letsencrypt.org/2015/11/09/why-90-days.html.
