### ISSUE TITLE
Version without webjob, "manual" certificate update only

### ISSUE THREAD

**Issue by saxx** [sjkp/letsencrypt-siteextension#92]
Thanks a lot for this great extension.

Is it possible to provide a version that does not install a webjob? A version where I would have to visit the Kudu portal and manually click something like "Refresh certificate" there?

I understand that in most cases the automatic renewal is a perfect fit. Nevertheless I would prefer not to have the webjob running, but rather to manually update the certificates (yes, I know, that sounds crazy). For example because in some scenarios I have deployments where all additional files are automatically removed (included the webjob).

Wouldn't the setup process of the extension also be much easier, because less settings are required if we don't have the webjob? Would we need a service user in that case?

**Comment by sjkp** [comment]
@saxx Yes it would make things simpler - but kinda goes against the principle of letsencrypt which is to automate things. 

I will consider making a separate version, without the web job but with a webhook (in addition to the UI) that people can automate how they want, I'm also not a huge fan of the webjobs as well as they do not function well when deployed with the extension.

**Comment by ohadschn** [comment]
A webhook would be a possible way to resolve https://github.com/sjkp/letsencrypt-siteextension/issues/43 too - just connect it to Azure function or MS Flow or whatever...

**Comment by ohadschn** [comment]
I created a standalone WebJob you could trigger manually:
https://github.com/ohadschn/letsencrypt-webapp-renewer

It also functions as a standalone command-line executable you can run from whenever (e.g. CI system).

**Comment by sjkp** [comment]
There's is now two versions of the app, one with a web job and one without. 

For the one without web jobs, you can automate the renewal of the certificates by calling the rest api at: 
`https://<yourwebapp>.scm.azurewebsites.net/letsencrypt/api/certificates/renew?api-version=2017-09-01`

You can call this endpoint using basic auth with the publishing credentials of the web app (read more here: http://wp.sjkp.dk/how-to-call-azure-web-app-api-hosted-inside-kudu/). 

You can call it as often as you want, it will only renew the certificate when there is 22 days or less left before it expires. (You can configure this using the app settings `letsencrypt:RenewXNumberOfDaysBeforeExpiration`) 

You can use, tools like azure functions, flow or logic apps to have a timer trigger a http call that gets executed daily which calls the endpoint. That is basically what the web job does today.
