### ISSUE TITLE
Question: Does the extension create a new cert for each domain or add them all to one cert?

### ISSUE THREAD

**Issue by ai-fwd** [sjkp/letsencrypt-siteextension#96]
Hi, I had a quick questions regarding my particular scenario which from going through the code and all the questions/issues I'm still not 100% sure on.

From what I understand this extension:
1) Can be used on multiple App Services under a single Resource Group #43 
2) Creates a web job per instance (i.e. App Service) and should point to a unique storage account #37 
3) Can support multiple domains per cert #5 
4) Does not automatically generate a new cert when a domain is added #90 

What I'm not sure about is, does the extension create a new cert for each top level domain and it's subdomains that is added to the app service  (i.e. foobar.com and www.foobar.com) or does it add all domains/sub-domains to a single cert (i.e. foobar.com, www.foobar.com, barfoo.com, www.barfoo.com, etc.)

I ask because the maximum domains you can assign to a cert is [100](https://community.letsencrypt.org/t/hi-we-have-one-domain-with-600-domainaliasses-the-maximum-allowed-in-one-certificate-is-100-aliasses-is-there-a-solution-to-get-a-certificate-for-all-these-domains-thanks/18750/4) so in my scenario i'd want to either have a new cert for each TLD or be able to split the domains across multiple certs.

Ideally i'd be able to have a cert for each TLD because as we add domains we wouldn't want to have to regenerate a cert again for 99 unrelated domains.

Hope all that makes sense.

Thanks in advanced -- and great extension!

**Comment by sjkp** [comment]
You can definately add multiple domains to the same certificate. I have however only tested with subdomains e.g. www.foobar.com and foobar.com. 

Reading up on lets encrypts forum https://community.letsencrypt.org/t/host-multiple-domains-with-a-single-certificate/20917/5 it should also be possible with different top level domain names in the same certificate, I have not tried that myself however. If that doesn't work. Please open a bug on it when you test it.
