### ISSUE TITLE
The SiteSlotName registered under application settings does not match the SiteSlotName you entered here 

### ISSUE THREAD

**Issue by jhansgit** [sjkp/letsencrypt-siteextension#98]
I am not sure what to enter here. during application registration a slot name was not required. I even don't know how to add a slot name to my application. 

Any ideas? Thanks

Thanks

**Comment by DavidDeSloovere** [comment]
I think it's when you have change the app settings in the portal, and this settings was empty, that maybe you get a NULL instead of an empty string or vice versa.

**Comment by sjkp** [comment]
I need to check up on this, if something has changed. I will do I tomorrow.
