### ISSUE TITLE
Certificate xxx was not found when clicking on "Request and install certificate"

### ISSUE THREAD

**Issue by aymeric-lagier** [sjkp/letsencrypt-siteextension#99]
Hi,

the following error occurs when click on "Request and install certificate".

![certificate not found](https://cloud.githubusercontent.com/assets/13032014/22589854/c0fec8c0-ea0c-11e6-83f1-dbc33183399a.png)

The certificate is created and visible in the "Ressources" pane of Azure portal but is not linked to my web app.

Any idea ?
Thanks

Aymeric

**Comment by justdmitry** [comment]
Check #53 and double-check that you set resource group for the app service plan correctly (`ServicePlanResourceGroupName`)

If everything correct - try to remember, did you moved App Plan to different resource group after it has been created? Move it back to "original" resource group :) I spent three hours today debugging this. I don't known why, may be something related to [MS restrictions when moving web apps](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-move-resources).

**Comment by sjkp** [comment]
#53 should answer your questions. If not please tell me what is unclear.

**Comment by Mcafee123** [comment]
Same Problem here. It has worked once with default web westeurope resourcegroup, but after "cleaning up" and moving all my web app services to the same new Resource Group, it stopped working with this error. AppServicePlan is in the same resource group as the web app service.

Server Error in '/letsencrypt' Application.

Certificate {GUID} was not found.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Microsoft.Rest.Azure.CloudException: Certificate 064192C0B20BFEC50571AE71C2978DA72F4DC71F was not found.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[CloudException: Certificate 064192C0B20BFEC50571AE71C2978DA72F4DC71F was not found.]
   Microsoft.Azure.Management.WebSites.<BeginCreateOrUpdateSiteWithHttpMessagesAsync>d__31.MoveNext() +4308
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Azure.Management.WebSites.<BeginCreateOrUpdateSiteAsync>d__53.MoveNext() +244
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Azure.Management.WebSites.SitesOperationsExtensions.BeginCreateOrUpdateSite(ISitesOperations operations, String resourceGroupName, String name, Site siteEnvelope, String skipDnsRegistration, String skipCustomDomainVerification, String forceDnsRegistration, String ttlInSeconds) +212
   LetsEncrypt.SiteExtension.Core.CertificateManager.Install(Target target, String pfxFilename, X509Certificate2 certificate) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:479
   LetsEncrypt.SiteExtension.Core.CertificateManager.Auto(Target binding) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:469
   LetsEncrypt.SiteExtension.Core.CertificateManager.RequestAndInstallInternal(Target target) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:263
   LetsEncrypt.SiteExtension.Controllers.HomeController.Install(RequestAndInstallModel model) +649
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +169
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9765121
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1590.0

**Comment by sjkp** [comment]
Thanks for the information, sounds like something is breaking when the site is being moved between resource groups. It is not a scenario that I have tested, but I will look into it.

**Comment by Mcafee123** [comment]
Thx a lot. I have used this https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/21872#.WKw5aRIrLMV blog entry to install all the stuff. I also tried to delete and recreate the Service Principal - without success.

**Comment by ukgrant** [comment]
I am also experiencing this issue. We moved our app between resources a while back. Is there a work around until a bug fix is in place?

**Comment by sjkp** [comment]
I will look into the issue over the weekend. So stay turned.

**Comment by modemgeek** [comment]
I have an open case with Microsoft on this issue.  Their feature expert (product group) has looked into  it.  They gave us 2 recommendations:
1.  Move app service plan back to original resource group.  I have tested it and it works
2. Fix in Let’s Encrypt site extension: The third party site extension uses an old version of the Microsoft.Azure.Management.WebSites C# SDK client (1.0.2-preview). They need to upgrade to 1.5.0-preview or later and set the serverFarmId property when creating the certificate object https://github.com/sjkp/letsencrypt-siteextension/blob/master/LetsEncrypt.SiteExtension.Core/CertificateManager.cs#L490. This would fix the issue for all customers running into this issue.

Would it be possible for you to try #2?

**Comment by sjkp** [comment]
I have actually upgraded it, and just need to test that it works, plus all the refactoring i did in the process. As I wanted to try that before I created my own bug report. So that is good news, if that solves it. Thanks you so much for the input. I will probably be able to release a new version before the weekend that solves it then.

**Comment by modemgeek** [comment]
I tried doing an upgrade and get the following error:

Failed to update Azure Let's Encrypt (x64) - System.IO.IOException: The process cannot access the file 'D:\home\SiteExtensions\letsencrypt64\bin\x64\libeay32.dll' because it is being used by another process. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) at System.IO.Abstractions.FileWrapper.OpenWrite(String path) at Kudu.Core.SiteExtensions.FeedExtensions.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__25.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__24.MoveNext()

After the error, the extension doesn't show up being installed.  I have to re-install it again and then it appears to be working.  I've tested it on 2 webapps so far.

**Comment by sjkp** [comment]
I haven't released the updated version of the site extension yet. I just pushed the source to github, but I'm still doing some testing. 

About the locked file, there is unfortunately not anything I can do about that (afaik).

**Comment by modemgeek** [comment]
Thanks.  I just updated after you closed the bug.  Seems much better now.  However, I did notice something different.  The certificates no longer show up under the Certificates header.  The binding is still there though.

**Comment by sjkp** [comment]
Yes that is an unfortunate side effect when the service plan have been moved, I'm unable to list them in the UI, as I don't know the name of the previous resource group, which they somehow are stilled listed under when the API is used to retrieve them. 

Once Microsoft answers my questions regarding how this is supposed to work I might be able to get it fixed - but for now I decided to not use more time on it, as is is really just guess work form my side, as there is ZERO documentation on it.

**Comment by Mcafee123** [comment]
after the update, everything works fine! thx a lot!
